const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        art_detail_1_title: "Bikin PT Semakin Mudah dengan Peraturan Baru Pemerintah!",
        art_detail_1_subtitle: "Mudahnya Bikin PT",
        art_badge: "Legalitas",
        art_full_title: "Bikin PT Semakin Mudah dengan Peraturan Baru Pemerintah!",
        art_highlight: "Mudahnya Bikin PT",
        art_p1: "Peraturan Pemerintah No. 8 Tahun 2021 tentang Modal Dasar Perseroan serta Pendaftaran Pendirian, Perubahan, dan Pembubaran Perseroan yang Memenuhi Kriteria Untuk Usaha Mikro dan Kecil resmi diteken oleh pemerintah bulan lalu. PP ini merupakan turunan dan aturan pendukung dari UU Cipta Kerja yang sudah lebih dulu disahkan tahun lalu.",
        art_p2: "PP No. 8 Tahun 2021 merupakan salah satu bentuk dukungan pemerintah untuk program kemudahan dalam berusaha (ease of doing business) di Indonesia. Dengan berlakunya PP ini maka terdapat berbagai aturan mengenai Perseroan Terbatas (PT) yang berubah. Salah satunya adalah adanya penyederhanaan persyaratan dalam pendirian PT. Untuk mengetahui lebih lanjut apa saja perubahannya, yuk simak penjelasan berikut.",
        art_sub_1: "Definisi Perseroan Terbatas",
        art_p3: "Dalam PP No.8 Tahun 2021, perseroan terbatas kini memiliki pengertian sebagai badan hukum yang merupakan persekutuan modal, didirikan berdasarkan perjanjian, melakukan kegiatan usaha dengan modal dasar yang seluruhnya terbagi dalam saham atau badan hukum perorangan yang memenuhi kriteria usaha mikro dan kecil.",
        art_p4: "Jika membandingkan dengan pengertian PT dalam UU No. 40 tahun 2007 maka terdapat tambahan badan usaha yang dapat dijadikan PT, yaitu perusahaan perorangan yang memenuhi kriteria usaha mikro dan kecil. Perseroan yang memenuhi kriteria untuk usaha mikro dan kecil yang dimaksud terdiri atas perseroan yang didirikan oleh dua orang atau lebih dan perseroan perorangan yang didirikan oleh satu orang. Dengan adanya aturan ini, pelaku usaha perorangan yang belum memiliki usaha dengan sekala besar tetap dapat memperoleh status sebagai badan hukum lho.",
        art_sub_2: "Kemudahan Modal & Syarat Pendirian",
        art_p5: "PP ini juga menyebutkan bahwa besaran modal dasar perseroan dapat ditentukan berdasarkan keputusan pendiri perseroan. Artinya sudah tidak ada lagi modal dasar yang harus dipenuhi oleh pendiri seperti yang diatur dalam UUPT sebelumnya. PP No. 8 Tahun 2021 juga mempermudah pendirian PT dengan cara menyederhanakan syarat pendiriannya.",
        art_p6: "Dalam aturan ini, PT yang berbentuk perseroan perorangan dapat didirikan oleh WNI yang sudah berusia 17 tahun dan cakap hukum. Pendiri perseroan juga hanya perlu mengisi pernyataan pendirian dalam bahasa Indonesia.",
        art_list_title: "Pernyataan pendirian harus memuat:",
        art_li1: "Nama dan tempat kedudukan perseroan perorangan.",
        art_li2: "Jangka waktu berdirinya perseroan perorangan.",
        art_li3: "Maksud dan tujuan serta kegiatan usaha perseroan perorangan.",
        art_li4: "Jumlah modal dasar, modal ditempatkan, dan modal disetor.",
        art_li5: "Nilai nominal dan jumlah saham.",
        art_li6: "Alamat perseroan perorangan.",
        art_li7: "Nama lengkap, tempat dan tanggal lahir, pekerjaan, tempat tinggal, nomor induk kependudukan, dan nomor pokok wajib pajak dari pendiri sekaligus direktur dan pemegang saham perseroan perorangan.",
        art_sub_3: "Status Badan Hukum Elektronik",
        art_p7: "Perseroan perorangan akan memperoleh status badan hukum setelah mendaftarkan pernyataan pendirian dan mendapatkan sertifikat pendaftaran secara elektronik. Karena hanya perlu mendaftar secara elektronik, perusahaan perseorangan/PT dengan kriteria UMKM tidak lagi memerlukan akta notaris dalam pendiriannya. Hal inilah yang membuat PT kini bisa didirikan tanpa notaris.",
        art_p8: "Perseroan perorangan yang telah memperoleh status badan hukum akan diumumkan dalam laman resmi Direktorat Jenderal Administrasi Hukum Umum (Ditjen AHU) Kementerian Hukum dan HAM. Sebagai bentuk penyederhanaan birokrasi, pelaku usaha juga dibebaskan dari kewajiban untuk mengumumkan pendirian PT nya dalam Tambahan Berita Negara.",
        important_label: "Penting untuk diingat:",
        important_text: "Bahwa ketentuan diatas hanya berlaku untuk PT dengan kriteria UMKM atau perusahaan perseorangan. Ketika perusahaan perseorangan mengalami perubahan dalam hal pemegang saham menjadi lebih dari satu orang dan/atau tidak lagi memenuhi kriteria sebagai UMKM, maka perseroan perorangan tersebut harus mengubah status badan hukumnya menjadi perseroan, hal ini diatur dalam Pasal 9 PP No. 8 Tahun 2021. Selain itu, perubahan status ke perseroan harus dilakukan dengan akta notaris dan didaftarkan secara elektronik kepada Menteri Hukum dan HAM melalui Ditjen AHU.",
        ref_label: "Referensi & Sumber:",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        art_detail_1_title: "Setting Up a PT is Easier with New Government Regulations!",
        art_detail_1_subtitle: "The Ease of PT Incorporation",
        art_badge: "Legality",
        art_full_title: "Setting Up a PT is Easier with New Government Regulations!",
        art_highlight: "The Ease of PT Incorporation",
        art_p1: "Government Regulation No. 8 of 2021 concerning the Company's Authorized Capital and the Registration of Establishment, Changes, and Dissolution of Companies that Meet the Criteria for Micro and Small Enterprises was officially signed by the government last month. This PP is a derivative and supporting regulation of the Job Creation Law which was passed last year.",
        art_p2: "PP No. 8 of 2021 is a form of government support for the ease of doing business program in Indonesia. With this PP, various rules regarding Limited Liability Companies (PT) have changed. One of them is the simplification of requirements for establishing a PT. To find out more about the changes, let's check the following explanation.",
        art_sub_1: "Definition of Limited Liability Company (PT)",
        art_p3: "In PP No. 8 of 2021, a limited liability company is now defined as a legal entity which is a capital partnership, established based on an agreement, conducting business activities with authorized capital entirely divided into shares or an individual legal entity that meets the criteria for micro and small businesses.",
        art_p4: "Comparing it with the definition of PT in Law No. 40 of 2007, there is an additional business entity that can be made into a PT: an individual company that meets the micro and small business criteria. This includes companies established by two or more people and individual companies established by one person. With this rule, individual entrepreneurs who do not yet have large-scale businesses can still obtain legal entity status.",
        art_sub_2: "Ease of Capital & Establishment Requirements",
        art_p5: "This PP also mentions that the amount of the company's authorized capital can be determined based on the decision of the company's founders. This means there is no longer a minimum authorized capital that must be met as regulated in the previous Company Law. PP No. 8 of 2021 also simplifies PT establishment by easing the requirements.",
        art_p6: "Under this rule, a PT in the form of an individual company can be established by an Indonesian citizen who is at least 17 years old and legally competent. The founder only needs to fill out an establishment statement in Indonesian.",
        art_list_title: "The establishment statement must include:",
        art_li1: "Name and domicile of the individual company.",
        art_li2: "The period of establishment of the individual company.",
        art_li3: "Purposes, objectives, and business activities of the individual company.",
        art_li4: "Amount of authorized, issued, and paid-up capital.",
        art_li5: "Nominal value and number of shares.",
        art_li6: "Address of the individual company.",
        art_li7: "Full name, place and date of birth, occupation, place of residence, national identity number, and tax identification number of the founder who is also the director and shareholder.",
        art_sub_3: "Electronic Legal Entity Status",
        art_p7: "An individual company will obtain legal entity status after registering the establishment statement and obtaining an electronic registration certificate. Since it only requires electronic registration, MSME companies no longer need a notary deed for establishment. This is what allows a PT to be established without a notary.",
        art_p8: "Individual companies that have obtained legal entity status will be announced on the official website of the Directorate General of General Legal Administration (Ditjen AHU) of the Ministry of Law and Human Rights. As a form of bureaucratic simplification, entrepreneurs are also exempted from the obligation to announce the establishment of their PT in the Supplement to the State Gazette.",
        important_label: "Important to remember:",
        important_text: "The above provisions only apply to PTs with MSME criteria or individual companies. When an individual company undergoes a change where shareholders become more than one person and/or no longer meets the MSME criteria, the individual company must change its legal status to a regular company, as regulated in Article 9 of PP No. 8 of 2021. Furthermore, the status change must be done with a notary deed and registered electronically with the Minister of Law and Human Rights.",
        ref_label: "References & Sources:",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        art_detail_1_title: "随着政府新规的出台，成立有限公司 (PT) 变得更加容易！",
        art_detail_1_subtitle: "轻松成立 PT",
        art_badge: "合法性",
        art_full_title: "随着政府新规的出台，成立有限公司 (PT) 变得更加容易！",
        art_highlight: "轻松成立 PT",
        art_p1: "政府上个月正式签署了关于公司基本资本以及满足中小微企业标准的公司的 2021 年第 8 号政府条例。该条例是去年通过的《创造就业法》的派生和配套规定。",
        art_p2: "2021 年第 8 号政府条例是政府支持印度尼西亚营商便利化计划的一种形式。随着该条例的生效，关于有限公司 (PT) 的各种规则发生了变化。其中之一是简化了成立有限公司的要求。要了解更多关于这些变化的信息，请查看以下解释。",
        art_sub_1: "有限公司 (PT) 的定义",
        art_p3: "在 2021 年第 8 号政府条例中，有限公司现在的定义是一个法人实体，它是资本伙伴关系，根据协议成立，通过完全分为股份的基础资本开展业务活动，或者是符合中小微企业标准的个人法人实体。",
        art_p4: "与 2007 年第 40 号法律中 PT 的定义相比，增加了一个可以转为 PT 的业务实体：符合中小微企业标准的个人公司。这包括由两人或多人成立的公司，以及由一人成立的个人公司。有了这项规定，还没有大规模业务的个人企业家仍然可以获得法人身份。",
        art_sub_2: "资金与成立要求的便利",
        art_p5: "该条例还提到，公司的法定资本额可以根据公司创始人的决定来确定。这意味着不再有之前公司法中规定的最低法定资本要求。2021 年第 8 号政府条例还通过放宽要求简化了 PT 的成立。",
        art_p6: "根据这项规定，个人公司形式的 PT 可以由年满 17 岁且具有法律能力的印度尼西亚公民成立。创始人只需要用印尼语填写一份成立声明。",
        art_list_title: "成立声明必须包括：",
        art_li1: "个人公司的名称和住所。",
        art_li2: "个人公司的成立期限。",
        art_li3: "个人公司的目的、目标和业务活动。",
        art_li4: "法定资本、已发行资本和实缴资本的金额。",
        art_li5: "面值和股份数量。",
        art_li6: "个人公司的地址。",
        art_li7: "创始人的全名、出生地和日期、职业、居住地、国民身份证号码和纳税识别号码（创始人同时担任董事和股东）。",
        art_sub_3: "电子法人地位",
        art_p7: "个人公司在登记成立声明并获得电子登记证后即可获得法人地位。由于只需要电子登记，中小微企业成立时不再需要公证契据。这就是现在可以无需公证人即可成立 PT 的原因。",
        art_p8: "获得法人地位的个人公司将在法律和人权部一般法律管理局 (Ditjen AHU) 的官方网站上公布。作为简化官僚机构的一种形式，企业家还被免除了在国家公报增刊上公布其 PT 成立情况的义务。",
        important_label: "重要提示：",
        important_text: "上述规定仅适用于符合中小微企业标准的 PT 或个人公司。当个人公司发生变化，股东人数变为一人以上和/或不再符合中小微企业标准时，该个人公司必须根据 2021 年第 8 号政府条例第 9 条的规定，将其法律地位变更为普通公司。此外，地位变更必须通过公证契据完成，并向法律和人权部进行电子登记。",
        ref_label: "参考资料与来源：",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});