const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        req_hero_title: "Syarat Penting yang Sering Terlewat Saat Mendirikan Badan Usaha PT",
        req_hero_subtitle: "Syarat Penting Saat Mendirikan PT",
        req_badge: "Legalitas",
        req_full_title: "Syarat Penting yang Sering Terlewat Saat Mendirikan Badan Usaha PT",
        req_highlight: "Syarat Penting Saat Mendirikan PT",
        req_p1: "Pendirian Perseroan Terbatas (PT) merupakan langkah strategis bagi para pengusaha untuk memulai bisnis secara resmi. Namun, proses pendirian PT tidak semudah membalik telapak tangan. Ada sejumlah persyaratan yang harus dipenuhi agar perusahaan dapat beroperasi secara legal.",
        req_p2: "Artikel ini akan memberikan gambaran lengkap mengenai syarat-syarat penting yang perlu diperhatikan dalam mendirikan badan usaha perseroan terbatas (PT), mulai dari persyaratan administratif hingga prosedur legal yang harus dilalui.",
        req_sub_1: "1. Pemilihan Nama Perusahaan",
        req_p3: "Pemilihan nama perusahaan merupakan langkah krusial. Nama yang baik adalah yang unik, mudah diingat, dan belum terdaftar. Sebaiknya dilakukan pengecekan terlebih dahulu melalui Direktorat Jenderal Administrasi Hukum Umum (Ditjen AHU).",
        req_str_ahu: "Direktorat Jenderal Administrasi Hukum Umum (Ditjen AHU)",
        req_p4: "Nama perusahaan tidak hanya berfungsi sebagai identitas legal, tetapi juga sebagai representasi dari merek perusahaan. Pemilihan nama harus dilakukan dengan cermat dan sesuai dengan peraturan perundang-undangan yang berlaku.",
        req_card_t: "Persyaratan Dasar Pendirian:",
        req_card_l1: "Minimal dua orang pendiri (Individu/Perusahaan).",
        req_card_l2: "Setiap pendiri wajib memiliki NPWP aktif.",
        req_card_l3: "Pembuatan Akta Pendirian melalui Notaris.",
        req_card_l4: "Penyusunan Anggaran Dasar perusahaan.",
        req_sub_2: "2. Struktur Modal Perseroan",
        req_p5: "Modal perseroan adalah aset atau uang yang disetorkan untuk menjalankan bisnis. Modal ini tidak hanya berupa uang tunai, tetapi bisa juga berupa aset seperti bangunan, mesin, atau hak paten yang dinilai dengan uang.",
        req_m1_t: "Modal Dasar",
        req_m1_d: "Jumlah total modal yang tercantum dalam dokumen resmi. Ini adalah target dana maksimal yang ingin dikumpulkan perusahaan.",
        req_m2_t: "Modal Disetor",
        req_m2_d: "Bagian modal yang sudah benar-benar dibayarkan ke perusahaan untuk membiayai operasional sehari-hari.",
        req_sub_3: "3. Izin Usaha dan Perizinan Tambahan",
        req_p6: "Izin usaha adalah surat resmi dari pemerintah (seperti BKPM) sebagai pengakuan bahwa perusahaan memenuhi syarat. Tanpa izin ini, perusahaan dianggap ilegal dan tidak mendapatkan perlindungan hukum.",
        req_warn_t: "Perizinan Tambahan:",
        req_warn_d: "Setiap jenis usaha memiliki kebutuhan berbeda. Perusahaan farmasi butuh izin produksi, sedangkan pertambangan butuh izin eksplorasi. Pastikan Anda memverifikasi izin spesifik sesuai bidang usaha Anda.",
        req_sub_4: "4. Pengurus, Direksi, dan Pajak",
        req_p7: "Dalam PT, terdapat dua kelompok pemimpin utama:",
        req_li1_t: "Pengurus:",
        req_li1_d: "Bertanggung jawab atas manajemen keseluruhan, seperti keuangan dan SDM.",
        req_li2_t: "Direksi:",
        req_li2_d: "Bagian pengurus yang menjalankan operasional sehari-hari (CEO/Direktur Utama).",
        req_p8: "Selain kepemimpinan, PT wajib taat pajak (PPh, PPN, dll). Laporan keuangan harus dilaporkan secara rutin untuk menjaga reputasi dan kepatuhan hukum perusahaan.",
        ref_label: "Referensi & Sumber:",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        req_hero_title: "Important Requirements Often Overlooked When Establishing a PT",
        req_hero_subtitle: "Important Requirements for PT Incorporation",
        req_badge: "Legality",
        req_full_title: "Important Requirements Often Overlooked When Establishing a PT",
        req_highlight: "Important Requirements for PT Incorporation",
        req_p1: "Establishing a Limited Liability Company (PT) is a strategic step for entrepreneurs to officially start a business. However, the process is not as simple as it seems. There are several requirements that must be met for the company to operate legally.",
        req_p2: "This article will provide a complete overview of the important requirements to consider when establishing a PT, ranging from administrative requirements to the legal procedures that must be followed.",
        req_sub_1: "1. Company Name Selection",
        req_p3: "Choosing a company name is a crucial step. A good name is unique, easy to remember, and not yet registered. It is advisable to check availability through the Directorate General of General Legal Administration (Ditjen AHU).",
        req_str_ahu: "Directorate General of General Legal Administration (Ditjen AHU)",
        req_p4: "A company name serves not only as a legal identity but also as a representation of the brand. Selection must be done carefully and in accordance with applicable laws and regulations.",
        req_card_t: "Basic Incorporation Requirements:",
        req_card_l1: "Minimum of two founders (Individuals/Companies).",
        req_card_l2: "Each founder must have an active Tax ID (NPWP).",
        req_card_l3: "Drafting of the Deed of Establishment through a Notary.",
        req_card_l4: "Drafting of the company's Articles of Association.",
        req_sub_2: "2. Company Capital Structure",
        req_p5: "Company capital consists of assets or money deposited to run the business. This capital is not only in the form of cash but can also be assets like buildings, machinery, or patents valued in monetary terms.",
        req_m1_t: "Authorized Capital",
        req_m1_d: "The total amount of capital stated in official documents. This is the maximum fund target the company aims to collect.",
        req_m2_t: "Paid-up Capital",
        req_m2_d: "The portion of capital that has been fully paid to the company to finance daily operations.",
        req_sub_3: "3. Business Licenses and Additional Permits",
        req_p6: "A business license is an official letter from the government (such as BKPM) as recognition that the company meets requirements. Without this, the company is considered illegal and lacks legal protection.",
        req_warn_t: "Additional Permits:",
        req_warn_d: "Each type of business has different needs. Pharmaceutical companies need production permits, while mining needs exploration permits. Ensure you verify specific permits according to your business field.",
        req_sub_4: "4. Management, Directors, and Taxes",
        req_p7: "In a PT, there are two main leadership groups:",
        req_li1_t: "Management:",
        req_li1_d: "Responsible for overall management, such as finance and HR.",
        req_li2_t: "Directors:",
        req_li2_d: "Part of management that runs daily operations (CEO/President Director).",
        req_p8: "In addition to leadership, a PT must be tax-compliant (Income Tax, VAT, etc.). Financial reports must be filed regularly to maintain reputation and legal compliance.",
        ref_label: "Reference & Source:",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        req_hero_title: "成立有限公司 (PT) 时经常被忽视的重要要求",
        req_hero_subtitle: "成立 PT 的重要条件",
        req_badge: "合法性",
        req_full_title: "成立有限公司 (PT) 时经常被忽视的重要要求",
        req_highlight: "成立 PT 的重要条件",
        req_p1: "成立有限公司 (PT) 是企业家正式开始业务的战略步骤。然而，这个过程并非易事。必须满足多项要求，公司才能合法运营。",
        req_p2: "本文将全面概述成立 PT 时需要注意的重要要求，从行政要求到必须遵循的法律程序。",
        req_sub_1: "1. 公司名称选择",
        req_p3: "选择公司名称是关键的一步。好的名称应该是独特的、易记的且未被注册的。建议先通过法律总局 (Ditjen AHU) 进行查询。",
        req_str_ahu: "法律总局 (Ditjen AHU)",
        req_p4: "公司名称不仅是法律身份，也是品牌的代表。选择时必须谨慎，并符合现行法律法规。",
        req_card_t: "基本成立要求：",
        req_card_l1: "至少两名创始人（个人/公司）。",
        req_card_l2: "每位创始人必须持有有效的纳税号 (NPWP)。",
        req_card_l3: "通过公证人起草成立契据。",
        req_card_l4: "起草公司章程。",
        req_sub_2: "2. 公司资本结构",
        req_p5: "公司资本是为运营业务而投入的资产或资金。资本不仅可以是现金，也可以是建筑物、机器或专利等资产（按货币价值评估）。",
        req_m1_t: "法定资本",
        req_m1_d: "官方文件中注明的资本总额。这是公司计划筹集的最高资金目标。",
        req_m2_t: "实收资本",
        req_m2_d: "已实际支付给公司用于日常运营的那部分资本。",
        req_sub_3: "3. 营业执照和额外许可",
        req_p6: "营业执照是政府（如 BKPM）颁发的正式文件，承认公司符合要求。没有该执照，公司将被视为非法并缺乏法律保护。",
        req_warn_t: "额外许可：",
        req_warn_d: "每种业务类型有不同的需求。制药公司需要生产许可证，而矿业需要勘探许可证。请务必根据您的业务领域核实特定许可。",
        req_sub_4: "4. 管理层、董事和税务",
        req_p7: "在 PT 中，有两个主要的领导群体：",
        req_li1_t: "管理层：",
        req_li1_d: "负责整体管理，如财务和人力资源。",
        req_li2_t: "董事：",
        req_li2_d: "负责日常运营的管理部分（首席执行官/总监）。",
        req_p8: "除领导层外，PT 必须遵守税务规定（所得税、增值税等）。财务报告必须定期申报，以维护声誉和法律合规。",
        ref_label: "参考资料与来源：",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});