const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        hero_title: "Hal-hal Penting yang Wajib Diketahui untuk Mendirikan PT",
        hero_subtitle: "Hal Penting untuk Mendirikan PT",
        imp_badge: "Legalitas",
        imp_full_title: "Hal-hal Penting yang Wajib Diketahui untuk Mendirikan PT",
        imp_highlight: "Hal Penting untuk Mendirikan PT",
        imp_p1: "Ketika akan memulai usaha, Anda membutuhkan sejumlah persiapan. Selain modal dan rencana bisnis, perusahaan juga sebaiknya berbadan hukum. Adanya badan hukum tidak hanya menjadi syarat pemenuhan legalitas, tetapi juga sebagai bukti bahwa integritas perusahaan Anda sudah teruji. Salah satu opsi badan usaha yang bisa Anda pilih adalah PT.",
        imp_intro_q: "Apa itu PT? Bagaimana langkah mendirikan PT? Apa saja persyaratan yang perlu Anda penuhi untuk mendirikan PT? Bagaimana pula prosedurnya? Simak selengkapnya dalam artikel ini!",
        imp_sub_1: "Apa Itu PT?",
        imp_p2: "PT atau perseroan terbatas merupakan salah satu badan hukum yang digunakan untuk menjalankan usaha. PT memiliki modal yang terdiri dari saham-sama yang sebagiannya dimiliki oleh pemilik PT itu sendiri.",
        imp_p3: "Menurut Undang-Undang No. 40 Tahun 2007, Perseroan Teritas adalah badan hukum persekutuan modal yang dibentuk dengan menggunakan perjanjian untuk melaksanakan aktivitas usaha. Modal PT terbagi dalam bentuk saham dengan persyaratan tertentu yang harus dipenuhi.",
        imp_sub_2: "Syarat Mendirikan PT",
        imp_p4: "Untuk bisa mendirikan PT, pemilik usaha perlu memenuhi sejumlah persyaratan sesuai yang tertera dalam Undang-Undang No. 40 Tahun 2007 dan Undang-Undang Cipta Kerja No. 11 Tahun 2020. Berikut penjelasannya:",
        imp_card1_t: "UU No. 40 Tahun 2007",
        imp_card1_l1: "Minimal didirikan oleh 2 orang dengan akta notaris.",
        imp_card1_l2: "Minimal 1 Komisaris dan 1 Direktur.",
        imp_card1_l3: "Nama PT lokal minimal 3 kata, tanpa bahasa asing.",
        imp_card1_l4: "Setoran modal minimal 25% dari total modal dasar.",
        imp_card1_l5: "PMA wajib modal dasar minimal Rp10 Miliar.",
        imp_card2_t: "UU Cipta Kerja No. 11/2020",
        imp_card2_l1: "PT bisa didirikan oleh 1 orang (khusus UMK).",
        imp_card2_l2: "Modal dasar minimal dihapuskan (lebih fleksibel).",
        imp_card2_l3: "TDP ditiadakan dan dialihkan ke NIB (Sistem OSS).",
        imp_card2_l4: "Perizinan dibagi berdasarkan tingkat risiko usaha.",
        imp_card2_l5: "AMDAL diganti SPPL untuk PT Perorangan (UMK).",
        imp_sub_3: "Berkas Administrasi yang Dibutuhkan",
        imp_doc1: "NPWP Penanggung Jawab PT",
        imp_doc2: "Salinan Kartu Keluarga (KK)",
        imp_doc3: "Salinan e-KTP Pemegang Saham",
        imp_doc4: "SKDP (Domisili) dari RT/RW",
        imp_doc5: "Foto Bangunan operasional tempat usaha",
        imp_sub_4: "Prosedur Pendirian PT",
        imp_step1_t: "1. Persiapkan Nama PT",
        imp_step1_d: "Penamaan harus mematuhi aturan: tidak bertentangan dengan norma, belum digunakan pihak lain, memakai huruf latin, dan tidak meniru lembaga pemerintah tanpa izin.",
        imp_step2_t: "2. Persiapkan Alamat/Lokasi PT",
        imp_step2_d: "Alamat harus sesuai lokasi operasional atau bisa menggunakan Virtual Office (VO). Perhatikan aturan zonasi daerah setempat.",
        imp_step3_t: "3. Tentukan Visi dan Misi",
        imp_step3_d: "Visi dan misi sebaiknya selaras dengan Klasifikasi Baku Lapangan Usaha Indonesia (KBLI) untuk memudahkan pengembangan model usaha.",
        imp_step4_t: "4. Penunjukan Pengurus",
        imp_step4_d: "Menetapkan Dewan Direksi sebagai pelaksana teknis dan Dewan Komisaris sebagai pemantau kinerja usaha.",
        imp_final_t: "Langkah Akhir Legalitas:",
        imp_final_1: "Pembuatan Akta Notaris: Mengurus akta melalui notaris yang terdaftar di Kemenkumham untuk menginput data ke AHU online/OSS.",
        imp_final_2: "Pengesahan Badan Hukum: Status badan hukum diperoleh setelah pendaftaran ke kementerian diterima dan bukti terbit.",
        imp_final_3: "Pengurusan Izin Usaha (OSS): Menggunakan akun OSS untuk memperoleh NIB dan mengurus perizinan operasional secara online.",
        ref_label: "Referensi & Sumber:",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        hero_title: "Essential Things You Must Know to Establish a PT",
        hero_subtitle: "Important Aspects of Establishing a PT",
        imp_badge: "Legality",
        imp_full_title: "Essential Things You Must Know to Establish a PT",
        imp_highlight: "Important Aspects of Establishing a PT",
        imp_p1: "When starting a business, you need several preparations. Besides capital and a business plan, a company should ideally be a legal entity. A legal entity is not only a requirement for legality but also proof of your company's tested integrity. One of the business entity options you can choose is a PT.",
        imp_intro_q: "What is a PT? What are the steps to establish one? What requirements do you need to fulfill? What is the procedure? Read more in this article!",
        imp_sub_1: "What is a PT?",
        imp_p2: "A PT (Perseroan Terbatas) or Limited Liability Company is a legal entity used to conduct business. A PT has capital consisting of shares, partly owned by the PT owners themselves.",
        imp_p3: "According to Law No. 40 of 2007, a PT is a legal entity of capital partnership formed using an agreement to carry out business activities. PT capital is divided into shares with specific requirements that must be met.",
        imp_sub_2: "Requirements for Establishing a PT",
        imp_p4: "To establish a PT, business owners need to meet several requirements as stated in Law No. 40 of 2007 and the Job Creation Law No. 11 of 2020. Here is the explanation:",
        imp_card1_t: "Law No. 40 of 2007",
        imp_card1_l1: "Minimum of 2 founders with a notary deed.",
        imp_card1_l2: "Minimum of 1 Commissioner and 1 Director.",
        imp_card1_l3: "Local PT name minimum 3 words, no foreign language.",
        imp_card1_l4: "Capital deposit minimum 25% of total authorized capital.",
        imp_card1_l5: "Foreign investment (PMA) requires min. Rp10 Billion capital.",
        imp_card2_t: "Job Creation Law No. 11/2020",
        imp_card2_l1: "PT can be founded by 1 person (SME only).",
        imp_card2_l2: "Minimum authorized capital abolished (more flexible).",
        imp_card2_l3: "TDP abolished and integrated into NIB (OSS System).",
        imp_card2_l4: "Licensing divided based on business risk level.",
        imp_card2_l5: "AMDAL replaced by SPPL for Individual PT (SMEs).",
        imp_sub_3: "Required Administrative Documents",
        imp_doc1: "Tax ID (NPWP) of the Person in Charge",
        imp_doc2: "Copy of Family Card (KK)",
        imp_doc3: "Copy of e-KTP of Shareholders",
        imp_doc4: "Domicile Certificate (SKDP) from local authorities",
        imp_doc5: "Photo of the business operational building",
        imp_sub_4: "PT Establishment Procedure",
        imp_step1_t: "1. Prepare the PT Name",
        imp_step1_d: "Naming must comply with rules: not contrary to norms, not used by others, using Latin letters, and not imitating govt agencies.",
        imp_step2_t: "2. Prepare PT Address/Location",
        imp_step2_d: "The address must match the operational location or can use a Virtual Office (VO). Note local zoning regulations.",
        imp_step3_t: "3. Determine Vision and Mission",
        imp_step3_d: "Vision and mission should align with the Indonesian Standard Industrial Classification (KBLI) for easier business development.",
        imp_step4_t: "4. Appointment of Management",
        imp_step4_d: "Appointing the Board of Directors as technical executors and the Board of Commissioners as performance monitors.",
        imp_final_t: "Final Legality Steps:",
        imp_final_1: "Notary Deed: Handling the deed through a registered notary to input data into AHU online/OSS.",
        imp_final_2: "Legalization: Legal status is obtained after ministry registration is accepted and proof is issued.",
        imp_final_3: "Business License (OSS): Using an OSS account to obtain NIB and manage operational licenses online.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        hero_title: "成立有限公司 (PT) 必须了解的重要事项",
        hero_subtitle: "成立 PT 的关键要素",
        imp_badge: "合法性",
        imp_full_title: "成立有限公司 (PT) 必须了解的重要事项",
        imp_highlight: "成立 PT 的关键要素",
        imp_p1: "在创业时，您需要多方面的准备。除了资金和商业计划，公司最好具备法人资格。法人身份不仅是合规要求，也是公司诚信经受考验的证明。有限公司 (PT) 是您可以选择的经营实体选项之一。",
        imp_intro_q: "什么是 PT？成立步骤有哪些？需要满足哪些条件？程序如何？请在本文中查看详情！",
        imp_sub_1: "什么是 PT？",
        imp_p2: "PT (Perseroan Terbatas) 或有限公司是用于开展业务的一种法人实体。PT 的资本由股份组成，部分由 PT 所有者本人持有。",
        imp_p3: "根据 2007 年第 40 号法律，有限公司是根据协议形成的资本合伙法人，旨在开展经营活动。PT 资本分为股份，并须满足特定要求。",
        imp_sub_2: "成立 PT 的条件",
        imp_p4: "要成立 PT，业主需满足 2007 年第 40 号法律和 2020 年第 11 号《综合性创造就业法》规定的若干要求：",
        imp_card1_t: "2007 年第 40 号法律",
        imp_card1_l1: "至少由 2 人通过公证契据成立。",
        imp_card1_l2: "至少有 1 名监事和 1 名董事。",
        imp_card1_l3: "本地 PT 名称至少包含 3 个单词，禁用外语。",
        imp_card1_l4: "实缴资本至少占总授权资本的 25%。",
        imp_card1_l5: "外资 (PMA) 要求最低资本为 100 亿印尼盾。",
        imp_card2_t: "2020 年第 11 号创造就业法",
        imp_card2_l1: "PT 可由 1 人成立（仅限中小微企业）。",
        imp_card2_l2: "取消最低授权资本要求（更具灵活性）。",
        imp_card2_l3: "取消 TDP，并入 NIB（OSS 系统）。",
        imp_card2_l4: "根据业务风险等级划分许可申请。",
        imp_card2_l5: "个人 PT（中小微企业）以 SPPL 代替 AMDAL。",
        imp_sub_3: "所需行政文件",
        imp_doc1: "PT 负责人的纳税号 (NPWP)",
        imp_doc2: "家庭卡 (KK) 复印件",
        imp_doc3: "股东身份证 (e-KTP) 复印件",
        imp_doc4: "当地颁发的住所证明 (SKDP)",
        imp_doc5: "营业场所运营建筑的照片",
        imp_sub_4: "成立 PT 的程序",
        imp_step1_t: "1. 准备 PT 名称",
        imp_step1_d: "命名须合规：不违反准则、未被他人使用、使用拉丁字母且不模仿政府机构。",
        imp_step2_t: "2. 准备 PT 地址/地点",
        imp_step2_d: "地址须与运营地点一致，也可使用虚拟办公室 (VO)。注意当地分区法规。",
        imp_step3_t: "3. 确定愿景和使命",
        imp_step3_d: "愿景和使命应与印尼标准行业分类 (KBLI) 一致，以便业务拓展。",
        imp_step4_t: "4. 任命管理层",
        imp_step4_d: "任命董事会作为执行机构，任命监事会作为业务监控机构。",
        imp_final_t: "最后的合法化步骤：",
        imp_final_1: "公证契据：通过注册公证人办理，将数据录入 AHU 在线/OSS 系统。",
        imp_final_2: "法人核准：在部门登记获批并颁发证明后获得法人身份。",
        imp_final_3: "经营许可 (OSS)：通过 OSS 账户获取 NIB 并在线办理运营许可。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});