const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        art2_hero_title: "Simak Persiapan Biaya dan Tips Menghemat Biaya Pendirian PT",
        art2_hero_subtitle: "Tips Menghemat Pendirian PT",
        cost_badge: "Legalitas",
        cost_full_title: "Simak Persiapan Biaya dan Tips Menghemat Biaya Pendirian PT",
        cost_highlight: "Tips Menghemat Pendirian PT",
        cost_p1: "Mendirikan perusahaan berbentuk Perseroan Terbatas (PT) di Indonesia merupakan langkah penting bagi banyak pengusaha. PT memberikan keuntungan berupa tanggung jawab terbatas bagi pemegang saham dan struktur bisnis yang lebih profesional. Namun, salah satu pertimbangan utama sebelum mendirikan PT adalah biaya yang dibutuhkan.",
        cost_p2: "Biaya pendirian PT dapat bervariasi tergantung pada beberapa faktor seperti lokasi, jasa notaris, dan jenis usaha. Artikel ini akan membahas secara rinci mengenai biaya pendirian PT, mulai dari prosedur hingga rincian biaya yang perlu disiapkan.",
        cost_p3: "Selain biaya, ada juga aspek-aspek legal dan administratif yang perlu dipertimbangkan. Dengan informasi yang tepat, Anda dapat meminimalisir risiko dan memastikan proses pendirian PT berjalan lancar.",
        cost_sub_1: "Proses Pendirian PT di Indonesia",
        cost_p4: "Untuk mempermudah Anda dalam proses pendirian PT, langkah awal yang perlu disiapkan dalam proses pendirian PT. Mengajukan Nama Perseroan Terbatas, Nama perusahaan harus diajukan dan disetujui oleh Kementerian Hukum dan HAM. Proses ini melibatkan:",
        cost_li_a: "Memeriksa ketersediaan nama: Nama perusahaan yang diajukan harus unik dan belum digunakan oleh perusahaan lain. Ini dapat dicek melalui Sistem Administrasi Badan Hukum (SABH).",
        cost_li_b: "Pengajuan nama secara online: Nama yang telah dipilih diajukan melalui SABH untuk mendapatkan persetujuan.",
        cost_list_title: "Tahapan Legalitas & Administrasi:",
        cost_s2_t: "1. Pembuatan Akta Pendirian PT",
        cost_s2_d: "Setelah nama disetujui, notaris menyusun akta yang memuat anggaran dasar, data pemegang saham, serta modal dasar dan ditempatkan.",
        cost_s3_t: "2. Pembuatan SKDP",
        cost_s3_d: "Surat Keterangan Domisili Perusahaan diajukan ke kantor kelurahan setempat sebagai bukti alamat resmi perusahaan.",
        cost_s4_t: "3. Pembuatan NPWP",
        cost_s4_d: "Pendaftaran di Kantor Pelayanan Pajak (KPP) sesuai domisili PT untuk mendapatkan identitas pajak perusahaan.",
        cost_s5_t: "4. Anggaran Dasar Perseroan",
        cost_s5_d: "Penyusunan dan pengajuan anggaran dasar kepada Kemenkumham melalui notaris untuk pengesahan resmi.",
        cost_s6_t: "5. Mengajukan SIUP",
        cost_s6_d: "Surat Izin Usaha Perdagangan diperlukan untuk legalitas kegiatan perdagangan, diajukan ke dinas terkait.",
        cost_s7_t: "6. Mengajukan TDP",
        cost_s7_d: "Tanda Daftar Perusahaan merupakan bukti resmi bahwa perusahaan Anda telah terdaftar secara sah di domisili terkait.",
        cost_s8_t: "7. Berita Acara Negara (BNRI):",
        cost_s8_d: "Langkah terakhir adalah mengumumkan pendirian PT di BNRI untuk memberikan informasi resmi kepada publik.",
        cost_sub_2: "Biaya-biaya yang Terlibat",
        cost_p5: "Dalam merencanakan pendirian PT, Anda perlu mempersiapkan anggaran untuk beberapa komponen biaya utama, antara lain:",
        cost_i1: "Biaya Notaris: Bervariasi tergantung notaris yang dipilih dan kompleksitas akta pendirian perusahaan.",
        cost_i2: "Biaya Pengajuan Nama: Biaya administrasi pengajuan nama ke Kementerian Hukum dan HAM.",
        cost_i3: "Biaya Pengesahan Badan Hukum: Pembayaran sejumlah biaya administrasi untuk mendapatkan pengesahan resmi.",
        cost_i4: "Biaya Pengurusan NPWP dan NIB: Meskipun relatif kecil, proses ini memerlukan persiapan dana operasional.",
        cost_i5: "Biaya Konsultasi: Biaya tambahan jika Anda memerlukan bantuan konsultan hukum atau akuntan.",
        cost_sub_3: "Tips Menghemat Biaya Pendirian PT",
        cost_p6: "Ada beberapa cara yang bisa Anda lakukan untuk mengelola anggaran pendirian PT secara lebih efektif:",
        tip1_t: "Jasa Konsultan",
        tip1_d: "Solusi efisien untuk mempercepat proses dan mengurangi risiko kesalahan administratif.",
        tip2_t: "Lokasi yang Tepat",
        tip2_d: "Beberapa daerah memiliki biaya administrasi yang berbeda; pilih yang paling strategis bagi bisnis.",
        tip3_t: "Kelola Anggaran",
        tip3_d: "Catat semua biaya yang dibutuhkan dan siapkan dana tambahan untuk biaya tak terduga.",
        tip4_t: "Manfaatkan Teknologi",
        tip4_d: "Gunakan platform online yang menawarkan layanan pengurusan dokumen secara murah dan efisien.",
        cost_cta: "Mendirikan PT di Indonesia memerlukan persiapan yang matang, termasuk perhitungan biaya yang tepat. Jika Anda membutuhkan bantuan, Anda dapat mempertimbangkan untuk menggunakan jasa dari Kontrak Hukum. Dengan layanan profesional dan pengalaman yang luas, Kontrak Hukum siap membantu Anda melalui setiap langkah proses pendirian PT dengan mudah dan efisien.",
        ref_label: "Referensi & Sumber:",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        art2_hero_title: "Check Cost Preparation and Tips for Saving on PT Incorporation Costs",
        art2_hero_subtitle: "Tips for Saving on PT Incorporation",
        cost_badge: "Legality",
        cost_full_title: "Understanding Cost Preparation and Tips for Saving on PT Incorporation",
        cost_highlight: "Tips for Saving on PT Incorporation",
        cost_p1: "Establishing a Limited Liability Company (PT) in Indonesia is a crucial step for many entrepreneurs. A PT offers benefits such as limited liability for shareholders and a more professional business structure. However, one of the primary considerations before starting is the required cost.",
        cost_p2: "PT establishment costs can vary based on factors like location, notary services, and the scale of the business. This article will discuss in detail the costs of establishing a PT, from procedures to the specific budget details you need to prepare. Understanding these costs is vital for aspiring entrepreneurs to plan their finances better.",
        cost_p3: "Beyond the costs, there are legal and administrative aspects to consider. With the right information, you can minimize risks and ensure the incorporation process runs smoothly. In this article, we also provide guides and tips to help you manage costs and the process effectively.",
        cost_sub_1: "PT Establishment Process in Indonesia",
        cost_p4: "To simplify the process, the first step involves Preparing the Name for the Limited Liability Company. The company name must be submitted and approved by the Ministry of Law and Human Rights. This process includes:",
        cost_li_a: "Checking name availability: The proposed company name must be unique and not yet used by another entity. This can be verified via the Legal Entity Administration System (SABH).",
        cost_li_b: "Online name submission: Once selected, the name is submitted through SABH for official approval.",
        cost_list_title: "Legal & Administrative Stages:",
        cost_s2_t: "1. Drafting the Deed of Establishment",
        cost_s2_d: "After the name is approved, a notary drafts the deed containing the articles of association, shareholder data, and capital structure.",
        cost_s3_t: "2. Obtaining the Domicile Certificate (SKDP)",
        cost_s3_d: "The SKDP is applied for at the local sub-district office as proof of the company's official business address.",
        cost_s4_t: "3. Obtaining the Tax ID (NPWP)",
        cost_s4_d: "Registration at the Tax Office (KPP) according to the PT's domicile to obtain the company's tax identity.",
        cost_s5_t: "4. Articles of Association",
        cost_s5_d: "Drafting and submitting the articles to the Ministry for official legalization through a notary.",
        cost_s6_t: "5. Applying for SIUP",
        cost_s6_d: "The Trading Business License is required for the legality of commercial activities, submitted to the relevant agency.",
        cost_s7_t: "6. Applying for TDP",
        cost_s7_d: "The Company Registration Certificate is official proof that your company is legally registered in its domicile.",
        cost_s8_t: "7. State Gazette (BNRI):",
        cost_s8_d: "The final step is to announce the PT establishment in the State Gazette to provide official public information.",
        cost_sub_2: "Involved Costs",
        cost_p5: "When planning for PT incorporation, you need to budget for several main cost components, including:",
        cost_i1: "Notary Fees: Varies depending on the chosen notary and the complexity of the deed.",
        cost_i2: "Name Application Fee: Administrative fee for submitting the name to the Ministry of Law and Human Rights.",
        cost_i3: "Legal Entity Legalization Fee: Payment of administrative fees to obtain official legal status.",
        cost_i4: "Tax ID and NIB Processing: While relatively small, these require operational fund preparation.",
        cost_i5: "Consultation Fees: Additional costs if you require assistance from legal consultants or accountants.",
        cost_sub_3: "Tips for Saving on PT Incorporation Costs",
        cost_p6: "There are several ways you can manage your PT incorporation budget more effectively:",
        tip1_t: "Consultant Services",
        tip1_d: "An efficient solution to speed up the process and reduce administrative errors.",
        tip2_t: "Right Location",
        tip2_d: "Some regions have different administrative costs; choose the most strategic one for your business.",
        tip3_t: "Budget Management",
        tip3_d: "Record all required costs and prepare extra funds for unexpected expenses.",
        tip4_t: "Leverage Technology",
        tip4_d: "Use online platforms that offer document management services at a low and efficient cost.",
        cost_cta: "Establishing a PT in Indonesia requires thorough preparation, including accurate cost calculation. If you need assistance, consider using services from Kontrak Hukum. With professional service and extensive experience, Kontrak Hukum is ready to help you through every step easily and efficiently.",
        ref_label: "Reference & Source:",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        art2_hero_title: "了解费用准备及节省成立有限公司 (PT) 费用的技巧",
        art2_hero_subtitle: "节省成立 PT 的技巧",
        cost_badge: "合法性",
        cost_full_title: "了解成立有限公司 (PT) 的费用准备及节省技巧",
        cost_highlight: "节省成立 PT 的技巧",
        cost_p1: "在印度尼西亚成立有限公司 (PT) 是许多企业家的重要一步。PT 提供股东有限责任和更专业的业务结构等优势。然而，成立 PT 之前的主要考虑因素之一是所需的费用。",
        cost_p2: "成立 PT 的费用因地点、公证服务和业务类型等多种因素而异。本文将详细探讨成立 PT 的费用，从程序到需要准备的预算细节。了解这些费用对于准企业家更好地规划财务至关重要。",
        cost_p3: "除了费用，还有法律和行政方面需要考虑。通过正确的信息，您可以最大限度地降低风险并确保成立过程顺利进行。在本文中，我们还将提供指南和技巧，帮助您有效管理成本和流程。",
        cost_sub_1: "印度尼西亚成立 PT 的流程",
        cost_p4: "为了简化流程，第一步涉及准备有限公司名称。公司名称必须提交给法律和人权部并获得批准。此过程包括：",
        cost_li_a: "检查名称可用性：拟议的公司名称必须是唯一的，且未被其他实体使用。这可以通过法律实体管理系统 (SABH) 进行验证。",
        cost_li_b: "在线提交名称：选定名称后，通过 SABH 提交以获得正式批准。",
        cost_list_title: "合法性与行政阶段：",
        cost_s2_t: "1. 起草成立契据",
        cost_s2_d: "名称获批后，公证人起草包含章程、股东数据和资本结构的契据。",
        cost_s3_t: "2. 办理住所证明 (SKDP)",
        cost_s3_d: "在当地村办事处申请，作为公司官方营业地址的证明。",
        cost_s4_t: "3. 办理纳税人识别号 (NPWP)",
        cost_s4_d: "根据 PT 的住所向税务局 (KPP) 登记，以获得公司的税务身份。",
        cost_s5_t: "4. 公司章程",
        cost_s5_d: "通过公证人向该部起草并提交章程以获得正式合法化。",
        cost_s6_t: "5. 申请 SIUP",
        cost_s6_d: "商业活动合法性所需的贸易营业执照，提交给相关机构。",
        cost_s7_t: "6. 申请 TDP",
        cost_s7_d: "公司登记证是您的公司在其住所合法注册的正式证明。",
        cost_s8_t: "7. 国家公报 (BNRI)：",
        cost_s8_d: "最后一步是在国家公报上公布 PT 的成立信息，以便公众了解正式信息。",
        cost_sub_2: "涉及的费用",
        cost_p5: "在计划成立 PT 时，您需要为几个主要的成本组成部分准备预算，包括：",
        cost_i1: "公证费：因所选公证人和契据的复杂程度而异。",
        cost_i2: "名称申请费：向法律和人权部提交名称的行政费用。",
        cost_i3: "法人实体合法化费：支付行政费用以获得正式法律地位。",
        cost_i4: "税号和 NIB 办理：虽然费用相对较小，但需要准备运营资金。",
        cost_i5: "咨询费：如果您需要法律顾问或会计师的帮助，则需支付额外费用。",
        cost_sub_3: "节省成立 PT 费用的技巧",
        cost_p6: "您可以通过以下几种方式更有效地管理成立 PT 的预算：",
        tip1_t: "顾问服务",
        tip1_d: "加快流程并减少行政错误的高效解决方案。",
        tip2_t: "选择正确的地点",
        tip2_d: "某些地区的行政费用有所不同；为您的业务选择最具战略意义的地点。",
        tip3_t: "预算管理",
        tip3_d: "记录所有需要的成本，并为意外支出准备额外资金。",
        tip4_t: "利用技术",
        tip4_d: "使用提供低廉且高效的文件管理服务的在线平台。",
        cost_cta: "在印度尼西亚成立 PT 需要充分准备，包括准确的成本计算。如果您需要帮助，请考虑使用 Kontrak Hukum 的服务。凭借专业的服务和丰富的经验，Kontrak Hukum 随时准备帮助您轻松高效地完成每一步。",
        ref_label: "参考资料与来源：",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});