const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        hero_1: "Jasa Legalitas, Perizinan & Sertifikasi Profesional",
        hero_2: "PT Oerusin Oerusan Kamoe menyediakan layanan legalitas, perizinan usaha & sertifikasi profesional.",
        tentang_1: "Tentang Oerusin",
        tentang_2: "Solusi Legalitas & Perizinan Bisnis yang Lebih Mudah",
        tentang_3: "Oerusin membantu pelaku usaha dalam proses legalitas secara cepat, transparan, dan profesional tanpa proses yang rumit.",
        tentang_4: "Pelajari Lebih Lanjut",
        service_1: "Layanan Kami",
        service_2: "Layanan Populer Kami",
        service_3: "Lihat Semua Layanan",
        service_4: "Mulai Dari",
        service_5: "Pelajari Layanan",
        alur_title: "Alur Pengurusan",
        alur_subtitle: "Proses mudah, transparan, dan terarah",
        step1_title: "Konsultasi",
        step1_desc: "Sampaikan kebutuhan usaha Anda",
        step2_title: "Dokumen",
        step2_desc: "Kami bantu persiapan dokumen",
        step3_title: "Proses",
        step3_desc: "Pengurusan sesuai regulasi",
        step4_title: "Selesai",
        step4_desc: "Izin terbit & siap digunakan",
        blog_badge: "Insight & Edukasi Bisnis",
        blog_title_1: "Artikel Legalitas",
        blog_title_2: "untuk Pengusaha Modern",
        blog_btn_all: "Lihat Semua Artikel →",
        blog_feat_badge: "Featured Insight",
        blog_feat_title: "Bikin PT Semakin Mudah dengan Peraturan Baru Pemerintah!",
        blog_feat_desc: "Mudahnya Bikin PT",
        blog_card_badge: "Artikel",
        blog_card1_title: "Simak Persiapan Biaya dan Tips Menghemat Biaya Pendirian PT",
        blog_card2_title: "Hal-hal Penting yang Wajib Diketahui untuk Mendirikan PT",
        faq_badge: "FAQ",
        faq_main_title: "Pertanyaan yang Sering Diajukan",
        faq_subtitle: "Temukan jawaban terkait proses legalitas, estimasi waktu, dan layanan Oerusin.",
        faq_btn: "Konsultasi Sekarang",
        testi_1: "Partner & Testimoni",
        testi_2: "Dipercaya oleh Perusahaan & Institusi",
        q1: "Dokumen apa saja yang perlu disiapkan untuk memulai pengurusan legalitas usaha?",
        a1: "Dokumen yang dibutuhkan umumnya meliputi KTP, NPWP, alamat usaha, serta data pendukung lainnya tergantung jenis layanan yang diajukan (seperti pendirian PT, NIB, atau sertifikasi). Tim kami akan memberikan checklist lengkap setelah konsultasi awal.",
        q2: "Apakah proses pengurusan bisa dilakukan secara online tanpa tatap muka?",
        a2: "Ya, seluruh proses dapat dilakukan secara online. Anda hanya perlu mengirimkan dokumen secara digital, dan tim kami akan menangani proses pengajuan hingga selesai tanpa perlu kehadiran langsung.",
        q3: "Apakah ada jaminan izin atau sertifikasi pasti terbit?",
        a3: "Kami memastikan proses pengurusan dilakukan sesuai prosedur dan regulasi yang berlaku. Namun, persetujuan akhir tetap menjadi kewenangan instansi terkait. Kami akan membantu meminimalkan risiko penolakan dengan memastikan kelengkapan dan kesesuaian dokumen sejak awal.",
        loc_1: "Lokasi Kantor",
        loc_2: "Kunjungi Kantor Oerusin",
        loc_3: "Tim kami siap membantu konsultasi legalitas dan perizinan bisnis secara langsung di kantor resmi Oerusin.",
        loc_4: "Buka di Google Maps →",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        hero_1: "Legality & Business Licensing Solutions",
        hero_2: "PT Oerusin Oerusan Kamoe provides professional business legality and licensing services.",
        tentang_1: "About Oerusin",
        tentang_2: "Easier Legality & Business Licensing Solutions",
        tentang_3: "Oerusin helps business actors in the legal process quickly, transparently, and professionally without complicated processes.",
        tentang_4: "Learn More",
        service_1: "Our Services",
        service_2: "Our Popular Services",
        service_3: "View All Services",
        service_4: "Start From",
        service_5: "Learn Services",
        alur_title: "Process Flow",
        alur_subtitle: "Easy, transparent, and directed process",
        step1_title: "Consultation",
        step1_desc: "Share your business needs with us",
        step2_title: "Documentation",
        step2_desc: "We assist with document preparation",
        step3_title: "Processing",
        step3_desc: "Handled according to regulations",
        step4_title: "Completion",
        step4_desc: "Permit issued & ready to use",
        blog_badge: "Business Insight & Education",
        blog_title_1: "Legality Articles",
        blog_title_2: "for Modern Entrepreneurs",
        blog_btn_all: "View All Articles →",
        blog_feat_badge: "Featured Insight",
        blog_feat_title: "Building a Company is Easier with New Government Regulations!",
        blog_feat_desc: "The Ease of Incorporating",
        blog_card_badge: "Article",
        blog_card1_title: "Budget Preparation and Tips to Save on Incorporation Costs",
        blog_card2_title: "Essential Things You Must Know to Establish a PT",
        faq_badge: "FAQ",
        faq_main_title: "Frequently Asked Questions",
        faq_subtitle: "Find answers regarding legality processes, estimated time, and Oerusin services.",
        faq_btn: "Consult Now",
        testi_1: "Partners & Testimonials",
        testi_2: "Trusted by Companies & Institutions",
        q1: "What documents need to be prepared to start processing business legality?Dokumen apa saja yang perlu disiapkan untuk memulai pengurusan legalitas usaha?",
        a1: "Required documents generally include an ID card (KTP), Taxpayer Identification Number (NPWP), business address, and other supporting data depending on the type of service requested (such as PT establishment, NIB, or certification). Our team will provide a complete checklist after the initial consultation.",
        q2: "Can the administration process be done online without face-to-face meetings?",
        a2: "Yes, the entire process can be done online. Simply submit your documents digitally, and our team will handle the application process from start to finish without the need for in-person attendance.",
        q3: "Is there a guarantee that the permit or certification will be issued?",
        a3: "We ensure the application process is carried out in accordance with applicable procedures and regulations. However, final approval remains the responsibility of the relevant agency. We will help minimize the risk of rejection by ensuring the completeness and accuracy of documents from the outset.",
        loc_1: "Office Location",
        loc_2: "Visit Oerusin Office",
        loc_3: "Our team is ready to assist with legal consultations and business permits directly at the official Oerusin office.",
        loc_4: "Open in Google Maps →",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        hero_1: "合法性与商业许可解决方案",
        hero_2: "PT Oerusin Oerusan Kamoe 提供专业的商业法律和许可服务",
        tentang_1: "关于奥鲁辛",
        tentang_2: "更便捷的合法性和商业许可解决方案",
        tentang_3: "Oerusin 帮助企业参与者快速、透明、专业地处理法律程序，无需复杂的流程。",
        tentang_4: "了解更多",
        service_1: "我们的服务",
        service_2: "我们的热门服务",
        service_3: "查看所有服务",
        service_4: "开始于",
        service_5: "学习服务",
        alur_title: "办理流程",
        alur_subtitle: "简单、透明、有针对性的流程",
        step1_title: "咨询",
        step1_desc: "告知我们您的业务需求",
        step2_title: "文件准备",
        step2_desc: "我们协助准备相关文件",
        step3_title: "办理中",
        step3_desc: "根据法规进行办理",
        step4_title: "完成",
        step4_desc: "签发许可证，即可使用",
        blog_badge: "商业见解与教育",
        blog_title_1: "法律文章",
        blog_title_2: "专为现代企业家打造",
        blog_btn_all: "查看所有文章 →",
        blog_feat_badge: "专题见解",
        blog_feat_title: "政府新规让成立公司变得更简单！",
        blog_feat_desc: "成立公司的简易性",
        blog_card_badge: "文章",
        blog_card1_title: "成立公司的预算准备与省钱技巧",
        blog_card2_title: "成立有限责任公司 (PT) 必须了解的重要事项",
        faq_badge: "常见问题",
        faq_main_title: "常见问题解答",
        faq_subtitle: "查找有关法律程序、预计时间和 Oerusin 服务的答案。",
        faq_btn: "立即咨询",
        testi_1: "合作伙伴与感言",
        testi_2: "深受企业和机构信赖",
        q1: "开始办理企业合法性手续需要准备哪些文件？",
        a1: "所需文件通常包括身份证（KTP）、纳税人识别号（NPWP）、公司地址以及其他辅助资料，具体取决于所申请的服务类型（例如私营公司注册、NIB 或认证）。我们的团队将在初次咨询后提供一份完整的清单。",
        q2: "行政流程能否在线完成，无需面对面会议？",
        a2: "是的，整个流程都可以在网上完成。您只需在线提交文件，我们的团队将全程负责您的申请流程，无需您亲自到场。",
        q3: "能否保证一定能颁发许可证或证书？",
        a3: "我们确保申请流程符合相关程序和规定。但是，最终审批权仍归相关机构所有。我们将从一开始就确保文件的完整性和准确性，从而最大限度地降低申请被拒的风险。",
        loc_1: "办公地点",
        loc_2: "访问 Oerusin 办公室",
        loc_3: "我们的团队随时准备在 Oerusin 官方办公室为您提供法律咨询和商业许可证方面的协助。",
        loc_4: "在谷歌地图中打开 →",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);
    
    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});