const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        iso_badge: "Sertifikasi",
        iso_title: "ISO 9001",
        iso_desc_title: "Deskripsi Layanan",
        iso_desc_p1: "ISO 9001 adalah standar internasional untuk Sistem Manajemen Mutu (SMM). Sertifikasi ini menunjukkan bahwa perusahaan Anda mampu secara konsisten menyediakan produk atau layanan yang memenuhi kebutuhan pelanggan serta persyaratan hukum dan peraturan yang berlaku.",
        iso_desc_p2: "Layanan di oerusin.id membantu perusahaan Anda meraih pengakuan global melalui pendampingan sertifikasi ISO 9001 yang terstruktur. Kami memandu Anda mulai dari tahap audit internal, perbaikan dokumentasi proses bisnis, hingga pelaksanaan audit eksternal oleh lembaga sertifikasi resmi. Dengan ISO 9001, bisnis Anda tidak hanya lebih efisien, tetapi juga memiliki daya saing kuat.",
        iso_benefit_title: "Manfaat ISO 9001",
        iso_benefit_1: "Meningkatkan efisiensi kerja & produktivitas karyawan.",
        iso_benefit_2: "Memenuhi syarat tender kelas menengah & besar.",
        iso_benefit_3: "Meminimalisir risiko kesalahan produk/layanan.",
        iso_support_title: "Pendampingan Kami",
        iso_support_1: "Audit kesenjangan (Gap Analysis).",
        iso_support_2: "Penyusunan dokumen SOP & manual mutu.",
        iso_support_3: "Koordinasi dengan Badan Sertifikasi Terakreditasi.",
        iso_get_title: "Apa yang Anda Dapatkan?",
        iso_get_1: "SK Kemenkumham",
        iso_get_2: "Akta Notaris",
        iso_get_3: "NPWP",
        iso_get_4: "OSS",
        iso_price_label: "Layanan",
        iso_price_value: "Rp 17.999.000",
        iso_cta: "Konsultasi Gratis",
        iso_feature_1: "Pengerjaan Cepat & Legal",
        iso_feature_2: "Monitoring Proses via WA",
        iso_guarantee_title: "Garansi Oerusin:",
        iso_guarantee_desc: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        iso_badge: "Certification",
        iso_title: "ISO 9001 Certification",
        iso_desc_title: "Service Description",
        iso_desc_p1: "ISO 9001 is the international standard for Quality Management Systems (QMS). This certification demonstrates that your company is capable of consistently providing products or services that meet customer needs as well as applicable legal and regulatory requirements.",
        iso_desc_p2: "Services at oerusin.id help your company achieve global recognition through structured ISO 9001 certification assistance. We guide you from the internal audit stage, business process documentation improvements, to the external audit conducted by official certification bodies. With ISO 9001, your business is not only more efficient but also highly competitive.",
        iso_benefit_title: "Benefits of ISO 9001",
        iso_benefit_1: "Improving work efficiency & employee productivity.",
        iso_benefit_2: "Meeting requirements for medium & large scale tenders.",
        iso_benefit_3: "Minimizing the risk of product/service errors.",
        iso_support_title: "Our Assistance",
        iso_support_1: "Gap Analysis audit.",
        iso_support_2: "Preparation of SOP documents & quality manuals.",
        iso_support_3: "Coordination with Accredited Certification Bodies.",
        iso_get_title: "What Do You Get?",
        iso_get_1: "Ministry of Law & HR Decree",
        iso_get_2: "Notary Deed",
        iso_get_3: "Tax ID (NPWP)",
        iso_get_4: "OSS Registration",
        iso_price_label: "Service",
        iso_price_value: "IDR 17,999,000",
        iso_cta: "Free Consultation",
        iso_feature_1: "Fast & Legal Processing",
        iso_feature_2: "Process Monitoring via WA",
        iso_guarantee_title: "Oerusin Guarantee:",
        iso_guarantee_desc: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        iso_badge: "认证",
        iso_title: "ISO 9001 认证",
        iso_desc_title: "服务描述",
        iso_desc_p1: "ISO 9001 是质量管理体系 (QMS) 的国际标准。该认证表明您的公司能够持续提供满足客户需求以及适用法律法规要求的产品或服务。",
        iso_desc_p2: "oerusin.id 的服务通过结构化的 ISO 9001 认证协助帮助您的公司获得全球认可。我们指导您完成内部审核、业务流程文档改进，直到由官方认证机构进行的外部审核。通过 ISO 9001，您的业务不仅效率更高，而且具有强大的竞争力。",
        iso_benefit_title: "ISO 9001 的优势",
        iso_benefit_1: "提高工作效率和员工生产力。",
        iso_benefit_2: "满足中大型项目投标的要求。",
        iso_benefit_3: "最大限度地降低产品或服务的错误风险。",
        iso_support_title: "我们的协助",
        iso_support_1: "差距分析 (Gap Analysis) 审核。",
        iso_support_2: "编写标准作业程序 (SOP) 文件和质量手册。",
        iso_support_3: "与认可的认证机构进行协调。",
        iso_get_title: "您将获得什么？",
        iso_get_1: "人权部批准信",
        iso_get_2: "公证契据",
        iso_get_3: "纳税人识别号 (NPWP)",
        iso_get_4: "OSS 系统注册",
        iso_price_label: "服务费用",
        iso_price_value: "17,999,000 印尼盾",
        iso_cta: "免费咨询",
        iso_feature_1: "快速且合法的办理流程",
        iso_feature_2: "通过 WhatsApp 实时监控进度",
        iso_guarantee_title: "Oerusin 保证:",
        iso_guarantee_desc: "确保您的法律文件真实有效，并已在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});