const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        ptnon_badge: "Legalitas",
        ptnon_title: "PT Non UMKM",
        ptnon_desc_t: "Deskripsi Layanan",
        ptnon_p1: "PT Non-UMKM adalah kendaraan hukum utama bagi para pelaku usaha yang menargetkan pasar skala menengah hingga besar. Dengan modal dasar yang lebih tinggi, badan usaha ini dirancang untuk menangani proyek-proyek besar, kerja sama antar-perusahaan korporasi, serta memenuhi syarat untuk mengikuti berbagai tender pemerintahan maupun swasta berskala nasional.",
        ptnon_p2: "Layanan di oerusin.id memastikan pendirian PT Non-UMKM Anda berjalan sesuai dengan standar hukum terbaru (OSS RBA). Kami memberikan pendampingan penuh mulai dari validasi modal dasar, penyusunan struktur pengurus yang kompleks, hingga pengurusan izin operasional yang spesifik sesuai dengan sektor industri Anda.",
        ptnon_adv_t: "Keunggulan PT Non-UMKM",
        ptnon_adv_l1: "Kredibilitas tinggi di mata perbankan & mitra global.",
        ptnon_adv_l2: "Mampu menangani tender dengan nilai kontrak besar.",
        ptnon_adv_l3: "Struktur manajemen yang lebih kuat & profesional.",
        ptnon_pkg_t: "Paket Eksekutif Oerusin",
        ptnon_pkg_l1: "Akta Notaris & SK Kemenkumham Lengkap.",
        ptnon_pkg_l2: "NIB, NPWP Badan, & Sertifikat Standar.",
        ptnon_pkg_l3: "Konsultasi Pemilihan KBLI & Risiko Bisnis.",
        ptnon_get_t: "Apa yang Anda Dapatkan?",
        ptnon_get_1: "SK Kemenkumham",
        ptnon_get_2: "Akta Notaris",
        ptnon_get_3: "NPWP",
        ptnon_get_4: "OSS",
        ptnon_svc_label: "Layanan",
        ptnon_price: "Rp 5.499.000",
        ptnon_btn_cta: "Konsultasi Gratis",
        ptnon_feat_1: "Pengerjaan Cepat & Legal",
        ptnon_feat_2: "Monitoring Proses via WA",
        ptnon_grnt_t: "Garansi Oerusin:",
        ptnon_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        ptnon_badge: "Legality",
        ptnon_title: "Non-MSME PT (Medium & Large Enterprise)",
        ptnon_desc_t: "Service Description",
        ptnon_p1: "Non-MSME PT is the primary legal vehicle for business owners targeting medium to large scale markets. With higher authorized capital, this business entity is designed to handle large projects, corporate B2B collaborations, and qualify for various national-scale government and private tenders.",
        ptnon_p2: "Services at oerusin.id ensure that your Non-MSME PT incorporation complies with the latest legal standards (OSS RBA). We provide full assistance from authorized capital validation, setting up complex management structures, to obtaining operational permits specific to your industrial sector.",
        ptnon_adv_t: "Advantages of Non-MSME PT",
        ptnon_adv_l1: "High credibility in the eyes of banks & global partners.",
        ptnon_adv_l2: "Capable of handling tenders with large contract values.",
        ptnon_adv_l3: "Stronger & more professional management structure.",
        ptnon_pkg_t: "Oerusin Executive Package",
        ptnon_pkg_l1: "Complete Notary Deed & Ministry of Law SK.",
        ptnon_pkg_l2: "NIB, Corporate NPWP, & Standard Certificate.",
        ptnon_pkg_l3: "Consultation on KBLI Selection & Business Risks.",
        ptnon_get_t: "What Will You Receive?",
        ptnon_get_1: "Ministry of Law Ratification",
        ptnon_get_2: "Notarial Deed",
        ptnon_get_3: "Corporate Tax ID (NPWP)",
        ptnon_get_4: "Online Single Submission (OSS)",
        ptnon_svc_label: "Service",
        ptnon_price: "IDR 5,499,000",
        ptnon_btn_cta: "Free Consultation",
        ptnon_feat_1: "Fast & Legal Processing",
        ptnon_feat_2: "Process Monitoring via WhatsApp",
        ptnon_grnt_t: "Oerusin Guarantee:",
        ptnon_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        ptnon_badge: "合法性",
        ptnon_title: "非中小微企业有限责任公司 (PT Non UMKM)",
        ptnon_desc_t: "服务说明",
        ptnon_p1: "非中小微企业有限责任公司 (PT Non-UMKM) 是针对大中型市场的企业主的主要法律载体。凭借较高的授权资本，该商业实体旨在处理大型项目、企业间合作，并有资格参与国家级政府和私人招标。",
        ptnon_p2: "oerusin.id 的服务可确保您的非中小微企业有限公司成立符合最新的法律标准 (OSS RBA)。我们提供全方位协助，从授权资本验证、设置复杂的管理结构，到获得特定于您工业部门的运营许可。",
        ptnon_adv_t: "非中小微企业有限公司的优势",
        ptnon_adv_l1: "在银行和全球合作伙伴眼中具有很高的可信度。",
        ptnon_adv_l2: "有能力处理大额合同的招标项目。",
        ptnon_adv_l3: "更强大、更专业的管理架构。",
        ptnon_pkg_t: "Oerusin 行政套餐",
        ptnon_pkg_l1: "完整的公证契约和司法部法令 (SK)。",
        ptnon_pkg_l2: "企业登记证 (NIB)、公司税号和标准证书。",
        ptnon_pkg_l3: "KBLI选择与商业风险咨询。",
        ptnon_get_t: "您 akan 获得什么？",
        ptnon_get_1: "司法部核准书",
        ptnon_get_2: "公证人契约",
        ptnon_get_3: "公司纳税号",
        ptnon_get_4: "OSS系统登记",
        ptnon_svc_label: "服务",
        ptnon_price: "5,499,000 印尼盾",
        ptnon_btn_cta: "免费咨询",
        ptnon_feat_1: "快速而合法的处理",
        ptnon_feat_2: "通过 WhatsApp 监控进度",
        ptnon_grnt_t: "Oerusin 担保：",
        ptnon_grnt_d: "确保您的法律文件真实并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});