const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        haki_badge: 'Sertifikasi',
        haki_title: 'Hak Paten/Haki',
        haki_desc_title: 'Deskripsi Layanan',
        haki_desc_p1: 'Hak Kekayaan Intelektual (HAKI) adalah perlindungan hukum atas hasil olah pikir, kreativitas, dan inovasi yang menghasilkan produk atau proses yang berguna bagi masyarakat. Di dunia bisnis, HAKI adalah aset berharga yang memberikan hak eksklusif kepada Anda untuk menggunakan, memproduksi, dan mengomersialkan karya atau merek Anda tanpa gangguan dari pihak lain.',
        haki_desc_p2: 'Layanan di oerusin.id membantu mengamankan identitas dan inovasi bisnis Anda melalui pendaftaran resmi ke DJKI (Direktorat Jenderal Kekayaan Intelektual). Kami memastikan proses pengecekan awal hingga submisi dokumen dilakukan dengan teliti guna meminimalisir risiko penolakan.',
        haki_why_title: 'Mengapa Perlu HAKI?',
        haki_why_1: 'Mencegah penyalahgunaan merek/karya oleh pihak lain.',
        haki_why_2: 'Meningkatkan nilai valuasi dan kredibilitas bisnis.',
        haki_why_3: 'Memberikan hak eksklusif untuk lisensi atau waralaba.',
        haki_type_title: 'Jenis Perlindungan',
        haki_type_1: 'Merek Dagang & Logo Bisnis.',
        haki_type_2: 'Hak Cipta (Karya Tulis, Musik, Software).',
        haki_type_3: 'Paten (Inovasi Teknologi/Alat) & Desain Industri.',
        haki_get_title: 'Apa yang Anda Dapatkan?',
        haki_get_1: 'SK Kemenkumham',
        haki_get_2: 'Sertifikat Resmi HAKI',
        haki_get_3: 'Pengecekan Plagiarisme',
        haki_get_4: 'Bantuan Hukum Awal',
        haki_price_label: 'Layanan',
        haki_price_value: 'Rp 3.599.000',
        haki_cta: 'Konsultasi Gratis',
        haki_feature_1: 'Pengerjaan Cepat & Legal',
        haki_feature_2: 'Monitoring Proses via WA',
        haki_guarantee_title: 'Garansi Oerusin:',
        haki_guarantee_desc: 'Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.',
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        haki_badge: 'Certification',
        haki_title: 'Patent / Intellectual Property',
        haki_desc_title: 'Service Description',
        haki_desc_p1: 'Intellectual Property Rights (IPR) is legal protection for the results of thought, creativity, and innovation that produce products or processes useful for society. In the business world, IPR is a valuable asset that gives you exclusive rights to use, produce, and commercialize your work or brand without interference from others.',
        haki_desc_p2: 'Services at oerusin.id help secure your business identity and innovation through official registration with the DJKI (Directorate General of Intellectual Property). We ensure the process from initial checking to document submission is carried out thoroughly to minimize the risk of rejection.',
        haki_why_title: 'Why Do You Need IPR?',
        haki_why_1: 'Prevent misuse of brands/works by other parties.',
        haki_why_2: 'Increase business valuation and credibility.',
        haki_why_3: 'Grant exclusive rights for licensing or franchising.',
        haki_type_title: 'Types of Protection',
        haki_type_1: 'Trademarks & Business Logos.',
        haki_type_2: 'Copyright (Written Works, Music, Software).',
        haki_type_3: 'Patents (Tech Innovations/Tools) & Industrial Design.',
        haki_get_title: 'What Do You Get?',
        haki_get_1: 'Ministry of Law & Human Rights Decree',
        haki_get_2: 'Official IPR Certificate',
        haki_get_3: 'Plagiarism Checking',
        haki_get_4: 'Initial Legal Assistance',
        haki_price_label: 'Service',
        haki_price_value: 'IDR 3,599,000',
        haki_cta: 'Free Consultation',
        haki_feature_1: 'Fast & Legal Process',
        haki_feature_2: 'Progress Monitoring via WA',
        haki_guarantee_title: 'Oerusin Guarantee:',
        haki_guarantee_desc: 'Your legal documents are guaranteed to be authentic and registered in the government system.',
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        haki_badge: '认证',
        haki_title: '专利/知识产权 (HAKI)',
        haki_desc_title: '服务描述',
        haki_desc_p1: '知识产权 (IPR) 是对产生对社会有用的产品或过程的思想、创造力和创新成果的法律保护。在商业世界中，知识产权是一项宝贵的资产，它赋予您使用、生产和商业化您的作品或品牌的专有权，而不受他人的干扰。',
        haki_desc_p2: 'Oerusin.id 的服务通过向 DJKI（知识产权总局）进行正式注册，帮助保护您的业务身份和创新。我们确保从初步检查到提交文件的整个过程都经过彻底执行，以尽量减少被拒绝的风险。',
        haki_why_title: '为什么需要知识产权？',
        haki_why_1: '防止其他方滥用品牌/作品。',
        haki_why_2: '提升企业估值和信誉。',
        haki_why_3: '授予许可或特许经营的专有权。',
        haki_type_title: '保护类型',
        haki_type_1: '商标与业务徽标。',
        haki_type_2: '著作权（文学作品、音乐、软件）。',
        haki_type_3: '专利（技术创新/工具）与工业设计。',
        haki_get_title: '您将获得什么？',
        haki_get_1: '法律与人权部法令 (SK)',
        haki_get_2: '官方知识产权证书',
        haki_get_3: '抄袭检查',
        haki_get_4: '初步法律援助',
        haki_price_label: '服务费',
        haki_price_value: '3,599,000 印尼盾',
        haki_cta: '免费咨询',
        haki_feature_1: '快捷且合法的办理',
        haki_feature_2: '通过 WhatsApp 监控进度',
        haki_guarantee_title: 'Oerusin 保证:',
        haki_guarantee_desc: '确保您的法律文件真实有效，并在政府系统中注册。',
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});