const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        ptp_badge: "Legalitas",
        ptp_title: "PT Perorangan",
        ptp_desc_t: "Deskripsi Layanan",
        ptp_p1: "PT Perorangan adalah solusi legalitas modern bagi Anda pelaku Usaha Mikro dan Kecil (UMK) yang ingin memiliki badan hukum tanpa harus melibatkan partner atau pemegang saham lain. Berdasarkan UU Cipta Kerja, kini Anda bisa mendirikan Perseroan Terbatas dengan status badan hukum resmi meski hanya memiliki satu orang pendiri yang sekaligus menjabat sebagai direktur.",
        ptp_p2: "Layanan di oerusin.id dirancang khusus untuk membantu pengusaha mandiri mendapatkan legalitas dengan proses yang sangat cepat, efisien, dan harga yang sangat kompetitif. Dengan memiliki PT Perorangan, bisnis Anda akan terlihat lebih kredibel di mata perbankan, investor, maupun saat mengikuti tender pengadaan barang dan jasa.",
        ptp_adv_t: "Keunggulan PT Perorangan",
        ptp_adv_l1: "Pemisahan harta pribadi dan perusahaan.",
        ptp_adv_l2: "Tarif pajak yang lebih rendah bagi UMK.",
        ptp_adv_l3: "Syarat pendirian sangat mudah dan simpel.",
        ptp_why_t: "Mengapa Lewat Oerusin?",
        ptp_why_l1: "Harga transparan mulai dari Rp 500rb.",
        ptp_why_l2: "Pendampingan pemilihan KBLI yang tepat.",
        ptp_why_l3: "Proses tuntas hanya dalam hitungan hari.",
        ptp_get_t: "Apa yang Anda Dapatkan?",
        ptp_get_1: "SK Kemenkumham",
        ptp_get_2: "Surat Keterangan Terdaftar",
        ptp_get_3: "NPWP",
        ptp_get_4: "KBLI",
        ptp_svc_label: "Layanan",
        ptp_price: "Rp 499.000",
        ptp_btn_cta: "Konsultasi Gratis",
        ptp_feat_1: "Pengerjaan Cepat & Legal",
        ptp_feat_2: "Monitoring Proses via WA",
        ptp_grnt_t: "Garansi Oerusin:",
        ptp_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        ptp_badge: "Legality",
        ptp_title: "Individual PT (PT Perorangan)",
        ptp_desc_t: "Service Description",
        ptp_p1: "Individual PT is a modern legality solution for Micro and Small Enterprise (MSE) owners who want to have a legal entity without involving partners or other shareholders. Based on the Job Creation Law, you can now establish a Limited Liability Company with official legal entity status even with only one founder who also serves as the director.",
        ptp_p2: "Services at oerusin.id are specifically designed to help independent entrepreneurs obtain legality through a very fast, efficient process at a competitive price. By having an Individual PT, your business will look more credible to banks, investors, and when participating in procurement tenders.",
        ptp_adv_t: "Advantages of Individual PT",
        ptp_adv_l1: "Separation of personal and company assets.",
        ptp_adv_l2: "Lower tax rates for Micro and Small Enterprises.",
        ptp_adv_l3: "Very easy and simple incorporation requirements.",
        ptp_why_t: "Why Choose Oerusin?",
        ptp_why_l1: "Transparent pricing starting from IDR 500k.",
        ptp_why_l2: "Assistance in choosing the correct KBLI (Business Classification).",
        ptp_why_l3: "Process completed within just a few days.",
        ptp_get_t: "What Will You Receive?",
        ptp_get_1: "Ministry of Law Decree (SK Kemenkumham)",
        ptp_get_2: "Certificate of Registration",
        ptp_get_3: "Tax ID (NPWP)",
        ptp_get_4: "KBLI (Business Classification)",
        ptp_svc_label: "Service",
        ptp_price: "IDR 499,000",
        ptp_btn_cta: "Free Consultation",
        ptp_feat_1: "Fast & Legal Processing",
        ptp_feat_2: "Process Monitoring via WhatsApp",
        ptp_grnt_t: "Oerusin Guarantee:",
        ptp_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        ptp_badge: "合法性",
        ptp_title: "个人有限责任公司 (PT Perorangan)",
        ptp_desc_t: "服务说明",
        ptp_p1: "个人有限责任公司是为希望拥有法人实体而无需合作伙伴或其他股东参与的微型和小型企业 (MSE) 业主提供的现代合法化解决方案。根据《创造就业法》，现在您可以成立一家具有正式法人地位的有限公司，即使只有一名创始人同时担任董事。",
        ptp_p2: "oerusin.id 的服务专门旨在帮助独立企业家以极快、高效且极具竞争力的价格获得合法性。拥有个人有限责任公司后，您的业务在银行、投资者眼中以及参加采购招标时将显得更加可信。",
        ptp_adv_t: "个人有限责任公司的优势",
        ptp_adv_l1: "个人财产与公司财产分离。",
        ptp_adv_l2: "针对微型和小型企业的较低税率。",
        ptp_adv_l3: "成立条件非常简单。 ",
        ptp_why_t: "为什么选择 Oerusin？",
        ptp_why_l1: "价格透明，50万印尼盾起。",
        ptp_why_l2: "协助选择正确的 KBLI（业务分类）。",
        ptp_why_l3: "仅需几天即可完成全部流程。",
        ptp_get_t: "您将获得什么？",
        ptp_get_1: "司法部法令 (SK Kemenkumham)",
        ptp_get_2: "注册证明书",
        ptp_get_3: "纳税号 (NPWP)",
        ptp_get_4: "业务分类 (KBLI)",
        ptp_svc_label: "服务",
        ptp_price: "499,000 印尼盾",
        ptp_btn_cta: "免费咨询",
        ptp_feat_1: "快速且合法的办理",
        ptp_feat_2: "通过 WhatsApp 监控进度",
        ptp_grnt_t: "Oerusin 保证：",
        ptp_grnt_d: "您的法律文件确保真实，并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});