const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        org_badge: 'Sertifikasi',
        org_title: 'Organisasi Perkumpulan',
        org_desc_title: 'Deskripsi Layanan',
        org_desc_p1: 'Organisasi Perkumpulan adalah badan hukum yang terdiri dari kumpulan orang yang didirikan untuk mewujudkan kesamaan maksud dan tujuan tertentu, baik di bidang hobi, profesi, sosial, maupun peminatan khusus lainnya, yang tidak bermaksud untuk membagi keuntungan kepada anggotanya.',
        org_desc_p2: 'Layanan di oerusin.id membantu komunitas atau asosiasi Anda menjadi entitas legal yang diakui pemerintah. Dengan status badan hukum, perkumpulan Anda dapat membuka rekening bank atas nama organisasi, menjalin kerja sama resmi, serta memiliki perlindungan hukum yang jelas.',
        org_benefit_title: 'Manfaat Badan Hukum',
        org_benefit_1: 'Organisasi lebih kredibel dan terpercaya.',
        org_benefit_2: 'Memudahkan pengajuan hibah atau dana bantuan resmi.',
        org_benefit_3: 'Kepemilikan aset atas nama organisasi, bukan pribadi.',
        org_service_title: 'Layanan Lengkap Kami',
        org_service_1: 'Akta Notaris Pendirian Perkumpulan.',
        org_service_2: 'SK Pengesahan Badan Hukum Kemenkumham.',
        org_service_3: 'Konsultasi Penyusunan AD/ART.',
        org_get_title: 'Apa yang Anda Dapatkan?',
        org_get_item1: 'SK Kemenkumham',
        org_get_item2: 'Akta Notaris',
        org_get_item3: 'NPWP',
        org_get_item4: 'OSS',
        org_price_label: 'Layanan',
        org_price_value: 'Rp 6.499.000',
        org_cta: 'Konsultasi Gratis',
        org_feature_1: 'Pengerjaan Cepat & Legal',
        org_feature_2: 'Monitoring Proses via WA',
        org_guarantee_title: 'Garansi Oerusin:',
        org_guarantee_desc: 'Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.',
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        org_badge: 'Certification',
        org_title: 'Association Organization',
        org_desc_title: 'Service Description',
        org_desc_p1: 'An Association Organization is a legal entity consisting of a group of people established to realize certain common goals and objectives, whether in hobbies, professions, social, or other specific interests, with no intention of distributing profits to its members.',
        org_desc_p2: 'Oerusin.id services help your community or association become a government-recognized legal entity. With legal entity status, your association can open a bank account in the organization\'s name, engage in official collaborations, and have clear legal protection for all officers and members.',
        org_benefit_title: 'Legal Entity Benefits',
        org_benefit_1: 'The organization becomes more credible and trusted.',
        org_benefit_2: 'Easier to apply for official grants or funding.',
        org_benefit_3: 'Asset ownership is in the organization\'s name, not personal.',
        org_service_title: 'Our Complete Services',
        org_service_1: 'Association Establishment Notary Deed.',
        org_service_2: 'Kemenkumham Legal Entity Approval Decree.',
        org_service_3: 'Articles of Association/Bylaws Drafting Consultation.',
        org_get_title: 'What Do You Get?',
        org_get_item1: 'Kemenkumham Decree',
        org_get_item2: 'Notary Deed',
        org_get_item3: 'NPWP (Tax ID)',
        org_get_item4: 'OSS System Registration',
        org_price_label: 'Service',
        org_price_value: 'IDR 6,499,000',
        org_cta: 'Free Consultation',
        org_feature_1: 'Fast & Legal Process',
        org_feature_2: 'Progress Monitoring via WA',
        org_guarantee_title: 'Oerusin Guarantee:',
        org_guarantee_desc: 'Your legal documents are guaranteed to be authentic and registered in government systems.',
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        org_badge: '认证',
        org_title: '社团组织',
        org_desc_title: '服务描述',
        org_desc_p1: '社团组织是由一群人为了实现特定的共同目标和宗旨而设立的法人实体，无论是在爱好、职业、社会还是其他特定兴趣领域，且无意向其成员分配利润。',
        org_desc_p2: 'Oerusin.id 服务协助您的社区或协会成为政府认可的法律实体。拥有法人地位后，您的协会可以以组织名义开设银行账户，开展官方合作，并为所有管理人员和成员提供明确的法律保护。',
        org_benefit_title: '法人实体的优势',
        org_benefit_1: '组织更具公信力和可信度。',
        org_benefit_2: '更易于申请官方拨款或资金支持。',
        org_benefit_3: '资产所有权归组织名下，而非个人。',
        org_service_title: '我们的完整服务',
        org_service_1: '社团设立公证契约。',
        org_service_2: '司法部 (Kemenkumham) 法人核准令。',
        org_service_3: '章程/细则起草咨询。',
        org_get_title: '您将获得什么？',
        org_get_item1: '司法部核准令',
        org_get_item2: '公证契约',
        org_get_item3: '税务登记证 (NPWP)',
        org_get_item4: 'OSS 系统登记',
        org_price_label: '服务费',
        org_price_value: '6,499,000 印尼盾',
        org_cta: '免费咨询',
        org_feature_1: '快捷且合法的办理',
        org_feature_2: '通过 WhatsApp 监控进度',
        org_guarantee_title: 'Oerusin 保证:',
        org_guarantee_desc: '您的法律文件确保真实，并已在政府系统注册。',
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});