const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        hll_badge: "Sertifikasi",
        hll_title: "Halal",
        hll_desc_t: "Deskripsi Layanan",
        hll_p1: "Sertifikasi Halal bukan lagi sekadar label tambahan, melainkan kewajiban hukum bagi para pelaku usaha di Indonesia. Melalui BPJPH (Badan Penyelenggara Jaminan Produk Halal), negara memastikan bahwa produk yang beredar telah memenuhi standar syariat yang ketat, mulai dari bahan baku hingga proses produksi.",
        hll_p2: "oerusin.id hadir sebagai mitra pendamping untuk memudahkan langkah Anda mendapatkan sertifikat halal. Kami membantu teknis pendaftaran melalui sistem SiHALAL, memastikan kesesuaian dokumen, hingga memberikan konsultasi mengenai Sistem Jaminan Produk Halal (SJPH).",
        hll_bene_t: "Manfaat Sertifikasi Halal",
        hll_bene_l1: "Meningkatkan kepercayaan & ketenangan konsumen.",
        hll_bene_l2: "Syarat mutlak menembus pasar ritel modern & ekspor.",
        hll_bene_l3: "Membangun Unique Selling Point (USP) yang kuat.",
        hll_flow_t: "Alur Pendampingan",
        hll_flow_l1: "Verifikasi kesiapan dokumen & NIB.",
        hll_flow_l2: "Input data ke portal SiHALAL secara akurat.",
        hll_flow_l3: "Pemantauan proses hingga sertifikat terbit.",
        hll_get_t: "Apa yang Anda Dapatkan?",
        hll_get_1: "Sertifikat BPJPH",
        hll_get_2: "Akun SiHALAL",
        hll_get_3: "Pendampingan",
        hll_get_4: "Konsultasi",
        hll_svc_label: "Layanan",
        hll_price: "Rp 9.999.000",
        hll_btn_cta: "Konsultasi Gratis",
        hll_feat_1: "Pengerjaan Cepat & Legal",
        hll_feat_2: "Monitoring Proses via WA",
        hll_grnt_t: "Garansi Oerusin:",
        hll_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        hll_badge: "Certification",
        hll_title: "Halal",
        hll_desc_t: "Service Description",
        hll_p1: "Halal Certification is no longer just an optional label but a legal obligation for business owners in Indonesia. Through BPJPH (Halal Product Assurance Organizing Agency), the state ensures that products circulating in the market meet strict Sharia standards, from raw materials to production processes.",
        hll_p2: "oerusin.id acts as a mentoring partner to simplify your steps in obtaining a halal certificate. We assist with technical registration through the SiHALAL system, ensure document compliance, and provide consultation on the Halal Product Assurance System (SJPH).",
        hll_bene_t: "Benefits of Halal Certification",
        hll_bene_l1: "Enhance consumer trust and peace of mind.",
        hll_bene_l2: "Absolute requirement for modern retail and export markets.",
        hll_bene_l3: "Build a strong Unique Selling Point (USP).",
        hll_flow_t: "Mentoring Workflow",
        hll_flow_l1: "Verification of documents and Business ID (NIB).",
        hll_flow_l2: "Accurate data input into the SiHALAL portal.",
        hll_flow_l3: "Process monitoring until the certificate is issued.",
        hll_get_t: "What Will You Receive?",
        hll_get_1: "BPJPH Certificate",
        hll_get_2: "SiHALAL Account",
        hll_get_3: "Step-by-step Mentoring",
        hll_get_4: "Professional Consultation",
        hll_svc_label: "Service",
        hll_price: "IDR 9,999,000",
        hll_btn_cta: "Free Consultation",
        hll_feat_1: "Fast & Legal Processing",
        hll_feat_2: "Process Monitoring via WhatsApp",
        hll_grnt_t: "Oerusin Guarantee:",
        hll_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        hll_badge: "认证",
        hll_title: "清真认证 (Halal)",
        hll_desc_t: "服务说明",
        hll_p1: "清真认证 (Halal) 不再仅仅是一个可选标签，而是印尼企业主的法律义务。通过 BPJPH（清真产品保障组织机构），国家确保市场上流通的产品从原材料到生产过程都符合严格的伊斯兰教法标准。",
        hll_p2: "oerusin.id 作为您的陪同合作伙伴，简化您获得清真证书的步骤。我们协助通过 SiHALAL 系统进行技术注册，确保文件合规，并提供有关清真产品保障系统 (SJPH) 的咨询。",
        hll_bene_t: "清真认证的好处",
        hll_bene_l1: "增强消费者的信任和安心感。",
        hll_bene_l2: "进入现代零售和出口市场的绝对要求。",
        hll_bene_l3: "建立强大的独特销售主张 (USP)。",
        hll_flow_t: "陪同流程",
        hll_flow_l1: "文件和业务登记证 (NIB) 的验证。",
        hll_flow_l2: "准确地将数据输入 SiHALAL 门户。",
        hll_flow_l3: "全程监控进度直至证书颁发。",
        hll_get_t: "您将获得什么？",
        hll_get_1: "BPJPH 证书",
        hll_get_2: "SiHALAL 账户",
        hll_get_3: "全程陪同办理",
        hll_get_4: "专业咨询",
        hll_svc_label: "服务",
        hll_price: "9,999,000 印尼盾",
        hll_btn_cta: "免费咨询",
        hll_feat_1: "快速合法的办理",
        hll_feat_2: "通过 WhatsApp 监控进度",
        hll_grnt_t: "Oerusin 保证：",
        hll_grnt_d: "确保您的法律文件真实并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});