const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        fnd_badge: "Legalitas",
        fnd_title: "Yayasan",
        fnd_desc_t: "Deskripsi Layanan",
        fnd_p1: "Yayasan adalah badan hukum yang terdiri atas kekayaan yang dipisahkan dan diperuntukkan untuk mencapai tujuan tertentu di bidang sosial, keagamaan, dan kemanusiaan. Berbeda dengan PT, Yayasan tidak memiliki anggota dan tidak bertujuan untuk membagikan keuntungan bagi para pengurusnya, melainkan fokus pada pengabdian masyarakat.",
        fnd_p2: "Di oerusin.id, kami membantu mewujudkan niat mulia Anda dengan pengurusan legalitas yayasan yang komprehensif. Kami memastikan seluruh syarat administratif, mulai dari nama yayasan yang unik hingga pengesahan resmi dari negara, terpenuhi dengan tepat.",
        fnd_char_t: "Karakteristik Yayasan",
        fnd_char_l1: "Fokus pada bidang Sosial, Agama, & Kemanusiaan.",
        fnd_char_l2: "Memiliki organ Pembina, Pengurus, dan Pengawas.",
        fnd_char_l3: "Status badan hukum memberikan perlindungan aset.",
        fnd_svc_t: "Layanan Oerusin",
        fnd_svc_l1: "Cek & Pemesanan Nama Yayasan.",
        fnd_svc_l2: "Penyusunan Akta Notaris Yayasan.",
        fnd_svc_l3: "SK Pengesahan Kemenkumham & NIB.",
        fnd_get_t: "Apa yang Anda Dapatkan?",
        fnd_get_1: "Akta Notaris",
        fnd_get_2: "SK Kemenkumham",
        fnd_get_3: "NPWP",
        fnd_get_4: "OSS",
        fnd_svc_label: "Layanan",
        fnd_price: "Rp 5.999.000",
        fnd_btn_cta: "Konsultasi Gratis",
        fnd_feat_1: "Pengerjaan Cepat & Legal",
        fnd_feat_2: "Monitoring Proses via WA",
        fnd_grnt_t: "Garansi Oerusin:",
        fnd_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        fnd_badge: "Legality",
        fnd_title: "Foundation",
        fnd_desc_t: "Service Description",
        fnd_p1: "A Foundation (Yayasan) is a legal entity consisting of separated assets dedicated to achieving specific goals in the social, religious, and humanitarian fields. Unlike a PT, a Foundation has no members and does not aim to distribute profits to its management, focusing instead on community service.",
        fnd_p2: "At oerusin.id, we help realize your noble intentions with comprehensive foundation legality management. We ensure all administrative requirements, from a unique foundation name to official state ratification, are accurately fulfilled.",
        fnd_char_t: "Foundation Characteristics",
        fnd_char_l1: "Focus on Social, Religious, & Humanitarian fields.",
        fnd_char_l2: "Managed by Board of Trustees, Management, and Supervisors.",
        fnd_char_l3: "Legal entity status provides asset protection.",
        fnd_svc_t: "Oerusin Services",
        fnd_svc_l1: "Foundation Name Check & Reservation.",
        fnd_svc_l2: "Drafting of Foundation Notarial Deed.",
        fnd_svc_l3: "Ministry of Law Ratification & NIB.",
        fnd_get_t: "What Will You Receive?",
        fnd_get_1: "Notarial Deed",
        fnd_get_2: "Ministry Decree (SK)",
        fnd_get_3: "Tax ID (NPWP)",
        fnd_get_4: "OSS Registration",
        fnd_svc_label: "Service",
        fnd_price: "IDR 5,999,000",
        fnd_btn_cta: "Free Consultation",
        fnd_feat_1: "Fast & Legal Processing",
        fnd_feat_2: "Process Monitoring via WhatsApp",
        fnd_grnt_t: "Oerusin Guarantee:",
        fnd_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        fnd_badge: "合法性",
        fnd_title: "基金会 (Yayasan)",
        fnd_desc_t: "服务说明",
        fnd_p1: "基金会 (Yayasan) 是一个由独立资产组成的法人实体，致力于实现社会、宗教和人道主义领域的特定目标。与有限公司 (PT) 不同，基金会没有成员，不以向管理层分配利润为目的，而是专注于社会公益服务。",
        fnd_p2: "在 oerusin.id，我们通过全面的基金会合法化管理协助您实现崇高意愿。我们确保准确满足所有行政要求，从独特的基金会名称到官方的国家批准。",
        fnd_char_t: "基金会特征",
        fnd_char_l1: "专注于社会、宗教和人道主义领域。",
        fnd_char_l2: "由理事会、管理层和监事会管理。",
        fnd_char_l3: "法人地位提供资产保护。",
        fnd_svc_t: "Oerusin 服务内容",
        fnd_svc_l1: "基金会名称查询与预订。",
        fnd_svc_l2: "起草基金会公证契约。",
        fnd_svc_l3: "司法部批准 (SK) 和业务登记号 (NIB)。",
        fnd_get_t: "您将获得什么？",
        fnd_get_1: "公证契约",
        fnd_get_2: "司法部法令 (SK)",
        fnd_get_3: "纳税号 (NPWP)",
        fnd_get_4: "OSS 登记",
        fnd_svc_label: "服务",
        fnd_price: "5,999,000 印尼盾",
        fnd_btn_cta: "免费咨询",
        fnd_feat_1: "快速合法的办理",
        fnd_feat_2: "通过 WhatsApp 监控进度",
        fnd_grnt_t: "Oerusin 保证：",
        fnd_grnt_d: "确保您的法律文件真实并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});