const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        sbujk_badge: "Sertifikasi",
        sbujk_title: "SBUJK",
        sbujk_desc_title: "Deskripsi Layanan",
        sbujk_desc_p1: "Sertifikat Badan Usaha Jasa Konstruksi (SBUJK) adalah bukti pengakuan formal atas tingkat kompetensi dan kemampuan usaha jasa konstruksi. Bagi perusahaan yang bergerak di bidang kontraktor atau konsultan, SBUJK merupakan dokumen wajib untuk mendapatkan Izin Usaha Jasa Konstruksi (IUJK) dan menjadi syarat mutlak untuk mengikuti lelang/tender proyek pemerintah maupun swasta.",
        sbujk_desc_p2: "Layanan di oerusin.id mempermudah birokrasi pendaftaran SBUJK Anda melalui sistem LSBU yang terintegrasi dengan OSS RBA. Kami mendampingi Anda dalam pemenuhan standar kualifikasi, mulai dari verifikasi tenaga ahli (SKK), kecukupan modal, hingga peralatan.",
        sbujk_benefit_title: "Manfaat SBUJK",
        sbujk_benefit_1: "Syarat utama mengikuti tender & lelang proyek.",
        sbujk_benefit_2: "Bukti legalitas dan kredibilitas teknis perusahaan.",
        sbujk_benefit_3: "Syarat mendapatkan Sertifikat Standar di sistem OSS.",
        sbujk_support_title: "Pendampingan Oerusin",
        sbujk_support_1: "Asistensi pemilihan klasifikasi & sub-klasifikasi.",
        sbujk_support_2: "Validasi kesesuaian dokumen Tenaga Ahli (SKK).",
        sbujk_support_3: "Proses submisi ke Portal Perizinan PUPR / LSBU.",
        sbujk_get_title: "Apa yang Anda Dapatkan?",
        sbujk_get_1: "SK Kemenkumham",
        sbujk_get_2: "Akta Notaris",
        sbujk_get_3: "NPWP",
        sbujk_get_4: "OSS",
        sbujk_price_label: "Layanan",
        sbujk_price_value: "Rp 3.999.000",
        sbujk_cta: "Konsultasi Gratis",
        sbujk_feature_1: "Pengerjaan Cepat & Legal",
        sbujk_feature_2: "Monitoring Proses via WA",
        sbujk_guarantee_title: "Garansi Oerusin:",
        sbujk_guarantee_desc: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        sbujk_badge: "Certification",
        sbujk_title: "SBUJK (Construction Business Certificate)",
        sbujk_desc_title: "Service Description",
        sbujk_desc_p1: "The Construction Entity Certificate (SBUJK) is formal recognition of the level of competence and capability of a construction service business. For companies engaged in contracting or consulting, SBUJK is a mandatory document to obtain a Construction Service Business License (IUJK) and is an absolute requirement for participating in government or private project tenders.",
        sbujk_desc_p2: "Services at oerusin.id simplify the bureaucracy of your SBUJK registration through the LSBU system integrated with OSS RBA. We assist you in meeting qualification standards, starting from professional expert verification (SKK), capital adequacy, to equipment.",
        sbujk_benefit_title: "Benefits of SBUJK",
        sbujk_benefit_1: "Main requirement for participating in project tenders & auctions.",
        sbujk_benefit_2: "Proof of technical legality and company credibility.",
        sbujk_benefit_3: "Requirement to obtain a Standard Certificate in the OSS system.",
        sbujk_support_title: "Oerusin Assistance",
        sbujk_support_1: "Assistance in choosing classification & sub-classification.",
        sbujk_support_2: "Validation of Professional Expert (SKK) document suitability.",
        sbujk_support_3: "Submission process to PUPR Licensing Portal / LSBU.",
        sbujk_get_title: "What Do You Get?",
        sbujk_get_1: "Ministry of Law & HR Decree",
        sbujk_get_2: "Notary Deed",
        sbujk_get_3: "Tax ID (NPWP)",
        sbujk_get_4: "OSS Registration",
        sbujk_price_label: "Service",
        sbujk_price_value: "IDR 3,999,000",
        sbujk_cta: "Free Consultation",
        sbujk_feature_1: "Fast & Legal Processing",
        sbujk_feature_2: "Process Monitoring via WA",
        sbujk_guarantee_title: "Oerusin Guarantee:",
        sbujk_guarantee_desc: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        sbujk_badge: "认证",
        sbujk_title: "SBUJK (建筑企业证书)",
        sbujk_desc_title: "服务描述",
        sbujk_desc_p1: "建筑企业证书 (SBUJK) 是对建筑服务业务能力和胜任程度的正式认可。对于从事承包或咨询的公司，SBUJK 是获得建筑业务许可证 (IUJK) 的必备文件，也是参加政府或私人项目投标的绝对要求。",
        sbujk_desc_p2: "oerusin.id 的服务通过与 OSS RBA 集成的 LSBU 系统简化了您的 SBUJK 注册手续。我们协助您达到资质标准，从专家验证 (SKK)、资本充足性到设备准备。",
        sbujk_benefit_title: "SBUJK 的优势",
        sbujk_benefit_1: "参加项目招标和拍卖的主要条件。",
        sbujk_benefit_2: "公司技术合法性和信誉的证明。",
        sbujk_benefit_3: "在 OSS 系统中获得标准证书的必要条件。",
        sbujk_support_title: "Oerusin 协助内容",
        sbujk_support_1: "协助选择分类和子分类。",
        sbujk_support_2: "验证专家人员 (SKK) 文件的合规性。",
        sbujk_support_3: "提交至 PUPR 许可门户 / LSBU 的流程办理。",
        sbujk_get_title: "您将获得什么？",
        sbujk_get_1: "人权部批准信",
        sbujk_get_2: "公证契据",
        sbujk_get_3: "纳税人识别号 (NPWP)",
        sbujk_get_4: "OSS 系统注册",
        sbujk_price_label: "服务费用",
        sbujk_price_value: "3,999,000 印尼盾",
        sbujk_cta: "免费咨询",
        sbujk_feature_1: "快速且合法的办理流程",
        sbujk_feature_2: "通过 WhatsApp 实时监控进度",
        sbujk_guarantee_title: "Oerusin 保证:",
        sbujk_guarantee_desc: "确保您的法律文件真实有效，并已在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});