const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        tax_badge: 'Sertifikasi',
        tax_title: 'Laporan Pajak',
        tax_desc_title: 'Deskripsi Layanan',
        tax_desc_p1: 'Laporan Pajak yang rapi dan tepat waktu adalah cerminan kesehatan sebuah perusahaan. Namun, memahami regulasi perpajakan yang terus berubah seringkali menyita waktu dan tenaga para pemilik bisnis. Kelalaian dalam pelaporan dapat berakibat pada sanksi administratif hingga denda.',
        tax_desc_p2: 'Layanan di oerusin.id dirancang untuk memberikan ketenangan bagi Anda. Tim ahli kami akan membantu menyusun, menghitung, dan melaporkan pajak (SPT Masa maupun Tahunan) sesuai dengan ketentuan terbaru. Kami memastikan perhitungan akurat dan efisien.',
        tax_why_title: 'Kenapa Harus Oerusin?',
        tax_why_1: 'Menghindari denda keterlambatan lapor.',
        tax_why_2: 'Perhitungan akurat sesuai regulasi DJP terbaru.',
        tax_why_3: 'Konsultasi mengenai efisiensi pajak yang legal.',
        tax_scope_title: 'Cakupan Layanan',
        tax_scope_1: 'Laporan SPT Masa (Bulanan) PPh & PPN.',
        tax_scope_2: 'Laporan SPT Tahunan Badan & Perorangan.',
        tax_scope_3: 'Pembuatan E-Billing & ID Billing Pajak.',
        tax_get_title: 'Apa yang Anda Dapatkan?',
        tax_get_item1: 'SK Kemenkumham',
        tax_get_item2: 'Akta Notaris',
        tax_get_item3: 'NPWP',
        tax_get_item4: 'OSS',
        tax_price_label: 'Layanan',
        tax_price_value: 'Rp 499.000',
        tax_cta: 'Konsultasi Gratis',
        tax_feature_1: 'Pengerjaan Cepat & Legal',
        tax_feature_2: 'Monitoring Proses via WA',
        tax_guarantee_title: 'Garansi Oerusin:',
        tax_guarantee_desc: 'Laporan Anda ditangani oleh konsultan pajak yang kompeten dan sesuai regulasi.',
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        tax_badge: 'Certification',
        tax_title: 'Tax Reporting',
        tax_desc_title: 'Service Description',
        tax_desc_p1: 'Neat and timely Tax Reports reflect the health of a company. However, understanding constantly changing tax regulations often consumes the time and energy of business owners. Negligence in reporting can result in administrative sanctions and fines.',
        tax_desc_p2: 'Services at oerusin.id are designed to give you peace of mind. Our team of experts will help prepare, calculate, and report taxes (Monthly and Annual SPT) in accordance with the latest regulations. We ensure your tax calculations are accurate and efficient.',
        tax_why_title: 'Why Choose Oerusin?',
        tax_why_1: 'Avoid late filing penalties.',
        tax_why_2: 'Accurate calculations based on latest DJP regulations.',
        tax_why_3: 'Consultation on legal tax efficiency.',
        tax_scope_title: 'Service Scope',
        tax_scope_1: 'Monthly SPT Reports (PPh & PPN).',
        tax_scope_2: 'Corporate & Individual Annual SPT Reports.',
        tax_scope_3: 'E-Billing & Tax ID Billing Creation.',
        tax_get_title: 'What Do You Get?',
        tax_get_item1: 'Kemenkumham Decree',
        tax_get_item2: 'Notary Deed',
        tax_get_item3: 'NPWP (Tax ID)',
        tax_get_item4: 'OSS System Registration',
        tax_price_label: 'Service',
        tax_price_value: 'IDR 499,000',
        tax_cta: 'Free Consultation',
        tax_feature_1: 'Fast & Legal Process',
        tax_feature_2: 'Progress Monitoring via WA',
        tax_guarantee_title: 'Oerusin Guarantee:',
        tax_guarantee_desc: 'Your reports are handled by competent tax consultants in accordance with regulations.',
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        tax_badge: '认证',
        tax_title: '税务申报',
        tax_desc_title: '服务描述',
        tax_desc_p1: '整齐且及时的税务报告反映了公司的健康状况。然而，理解不断变化的税务法规往往会消耗企业主的时间和精力。申报疏忽可能导致行政处罚和罚款。',
        tax_desc_p2: 'Oerusin.id 的服务旨在让您安心。我们的专家团队将根据最新规定协助准备、计算和申报税款（月度及年度 SPT）。我们确保您的税务计算准确且高效。',
        tax_why_title: '为什么选择 Oerusin？',
        tax_why_1: '避免逾期申报罚款。',
        tax_why_2: '基于最新税务局 (DJP) 法规的准确计算。',
        tax_why_3: '合法节税咨询。',
        tax_scope_title: '服务范围',
        tax_scope_1: '月度 SPT 申报 (所得税与增值税)。',
        tax_scope_2: '企业及个人年度 SPT 申报。',
        tax_scope_3: '创建电子缴款单 (E-Billing)。',
        tax_get_title: '您将获得什么？',
        tax_get_item1: '司法部核准令',
        tax_get_item2: '公证契约',
        tax_get_item3: '税务登记证 (NPWP)',
        tax_get_item4: 'OSS 系统登记',
        tax_price_label: '服务费',
        tax_price_value: '499,000 印尼盾',
        tax_cta: '免费咨询',
        tax_feature_1: '快捷且合法的办理',
        tax_feature_2: '通过 WhatsApp 监控进度',
        tax_guarantee_title: 'Oerusin 保证:',
        tax_guarantee_desc: '您的报告由称职的税务顾问根据法规处理。',
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});