const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        kop_badge: "Sertifikasi",
        kop_title: "Koperasi",
        kop_desc_title: "Deskripsi Layanan",
        kop_desc_p1: "Koperasi adalah badan hukum yang didirikan oleh orang perseorangan atau badan hukum koperasi, dengan pemisahan kekayaan para anggotanya sebagai modal untuk menjalankan usaha, yang memenuhi aspirasi dan kebutuhan bersama di bidang ekonomi, sosial, dan budaya sesuai dengan nilai dan prinsip koperasi.",
        kop_desc_p2: "Di oerusin.id, kami mendukung gerakan ekonomi gotong royong dengan memfasilitasi pendirian koperasi yang legal dan terstruktur. Kami membantu mulai dari tahap persiapan rapat pembentukan hingga pengesahan kementerian.",
        kop_value_title: "Nilai Tambah Koperasi",
        kop_value_1: "Mengutamakan kesejahteraan anggota dibanding profit semata.",
        kop_value_2: "Keputusan diambil secara demokratis (Rapat Anggota).",
        kop_value_3: "Membangun ekosistem ekonomi yang kuat di komunitas.",
        kop_service_title: "Layanan Oerusin",
        kop_service_1: "Pendampingan Penyusunan Anggaran Dasar.",
        kop_service_2: "Akta Pendirian oleh Notaris Pembuat Akta Koperasi.",
        kop_service_3: "SK Pengesahan & NIB Koperasi.",
        kop_get_title: "Apa yang Anda Dapatkan?",
        kop_get_item1: "SK Kemenkumham",
        kop_get_item2: "Akta Notaris",
        kop_get_item3: "NPWP",
        kop_get_item4: "OSS",
        kop_price_label: "Layanan",
        kop_price_value: "Rp 5.999.000",
        kop_cta: "Konsultasi Gratis",
        kop_feature_1: "Pengerjaan Cepat & Legal",
        kop_feature_2: "Monitoring Proses via WA",
        kop_guarantee_title: "Garansi Oerusin:",
        kop_guarantee_desc: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        kop_badge: 'Certification',
        kop_title: 'Cooperative',
        kop_desc_title: 'Service Description',
        kop_desc_p1: 'A Cooperative is a legal entity established by individuals or cooperative legal entities, with the separation of its members\' wealth as capital for business operations, meeting common economic, social, and cultural aspirations.',
        kop_desc_p2: 'At oerusin.id, we support the mutual cooperation economic movement by facilitating the establishment of legal and structured cooperatives. We assist from the formation meeting to ministerial legalization.',
        kop_value_title: 'Cooperative Added Value',
        kop_value_1: 'Prioritizing member welfare over mere profit.',
        kop_value_2: 'Decisions are made democratically (Members\' Meeting).',
        kop_value_3: 'Building a strong economic ecosystem within the community.',
        kop_service_title: 'Oerusin Services',
        kop_service_1: 'Assistance in Drafting Articles of Association.',
        kop_service_2: 'Establishment Deed by a Cooperative Deed Notary.',
        kop_service_3: 'Approval Decree & Cooperative NIB.',
        kop_get_title: 'What Do You Get?',
        kop_get_item1: 'Kemenkumham Decree',
        kop_get_item2: 'Notary Deed',
        kop_get_item3: 'NPWP (Tax ID)',
        kop_get_item4: 'OSS System Registration',
        kop_price_label: 'Service',
        kop_price_value: 'IDR 5,999,000',
        kop_cta: 'Free Consultation',
        kop_feature_1: 'Fast & Legal Process',
        kop_feature_2: 'Progress Monitoring via WA',
        kop_guarantee_title: 'Oerusin Guarantee:',
        kop_guarantee_desc: 'Your legal documents are guaranteed to be authentic and registered in government systems.',
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        kop_badge: '认证',
        kop_title: '合作社',
        kop_desc_title: '服务描述',
        kop_desc_p1: '合作社是由个人或合作社法人设立的法人实体，其成员财产分离作为经营资本，旨在满足共同的经济、社会和文化愿望。',
        kop_desc_p2: '在 oerusin.id，我们通过协助建立合法且结构化的合作社，支持互助经济运动。我们协助从筹备会议到部级批准的全过程。',
        kop_value_title: '合作社附加值',
        kop_value_1: '优先考虑成员福利而非纯粹利润。',
        kop_value_2: '民主决策（成员大会）。',
        kop_value_3: '在社区内建立强大的经济生态系统。',
        kop_service_title: 'Oerusin 服务',
        kop_service_1: '协助起草章程。',
        kop_service_2: '由合作社公证人办理设立契约。',
        kop_service_3: '核准令及合作社商业登记号(NIB)。',
        kop_get_title: '您将获得什么？',
        kop_get_item1: '司法部(Kemenkumham)核准令',
        kop_get_item2: '公证契约',
        kop_get_item3: '税务登记证(NPWP)',
        kop_get_item4: 'OSS系统登记',
        kop_price_label: '服务费',
        kop_price_value: '5,999,000 印尼盾',
        kop_cta: '免费咨询',
        kop_feature_1: '快捷且合法的办理',
        kop_feature_2: '通过 WhatsApp 监控进度',
        kop_guarantee_title: 'Oerusin 保证:',
        kop_guarantee_desc: '您的法律文件确保真实，并已在政府系统注册。',
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});