const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        pma_badge: "Legalitas",
        pma_title: "PT PMA",
        pma_desc_t: "Deskripsi Layanan",
        pma_p1: "PT PMA (Penanaman Modal Asing) adalah bentuk badan hukum yang memungkinkan investor asing, baik perorangan maupun perusahaan luar negeri, untuk menjalankan bisnis secara resmi di wilayah Indonesia. Pendirian PT PMA tunduk pada regulasi yang lebih spesifik dibandingkan perusahaan lokal, termasuk pematuhan terhadap Daftar Positif Investasi (DPI).",
        pma_p2: "Layanan di oerusin.id memberikan solusi end-to-end bagi investor global. Kami menjembatani segala kebutuhan administratif dan birokrasi, mulai dari penentuan komposisi saham, pengurusan Akta Notaris, hingga legalitas dari Kemenkumham dan OSS RBA. Kami memastikan proses investasi Anda berjalan aman, cepat, dan sepenuhnya sesuai dengan hukum yang berlaku di Indonesia.",
        pma_adv_t: "Keunggulan PT PMA",
        pma_adv_l1: "Hak kepemilikan modal asing hingga 100% (tergantung KBLI).",
        pma_adv_l2: "Akses penuh untuk operasional bisnis di pasar Indonesia.",
        pma_adv_l3: "Mempermudah pengurusan izin tinggal terbatas (KITAS) bagi TKA.",
        pma_inv_t: "Layanan Investasi Kami",
        pma_inv_l1: "Asistensi Daftar Positif Investasi (DPI).",
        pma_inv_l2: "Akta Pendirian & SK Pengesahan Kemenkumham.",
        pma_inv_l3: "NIB, NPWP Badan, & Hak Akses OSS RBA.",
        pma_get_t: "Apa yang Anda Dapatkan?",
        pma_get_1: "SK Kemenkumham",
        pma_get_2: "Akta Notaris",
        pma_get_3: "NPWP Badan",
        pma_get_4: "NIB & Akses OSS RBA",
        pma_svc_label: "Layanan",
        pma_price: "Rp 10.499.000",
        pma_btn_cta: "Konsultasi Gratis",
        pma_feat_1: "Pengerjaan Cepat & Legal",
        pma_feat_2: "Monitoring Proses via WA",
        pma_grnt_t: "Garansi Oerusin:",
        pma_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        pma_badge: "Legality",
        pma_title: "FDI Company (PT PMA)",
        pma_desc_t: "Service Description",
        pma_p1: "PT PMA (Foreign Direct Investment) is a legal entity that allows foreign investors, both individuals and foreign companies, to officially conduct business within the territory of Indonesia. The establishment of a PT PMA is subject to more specific regulations compared to local companies, including compliance with the Positive Investment List (DPI).",
        pma_p2: "Services at oerusin.id provide end-to-end solutions for global investors. We bridge all administrative and bureaucratic needs, from determining share composition and processing Notarial Deeds to obtaining legalities from the Ministry of Law and Human Rights and OSS RBA. We ensure your investment process is secure, fast, and fully compliant with Indonesian law.",
        pma_adv_t: "Advantages of PT PMA",
        pma_adv_l1: "Foreign ownership rights up to 100% (depending on business sector/KBLI).",
        pma_adv_l2: "Full access to business operations in the Indonesian market.",
        pma_adv_l3: "Easier processing of limited stay permits (KITAS) for foreign workers.",
        pma_inv_t: "Our Investment Services",
        pma_inv_l1: "Positive Investment List (DPI) Assistance.",
        pma_inv_l2: "Deed of Establishment & Ministry Approval Decree.",
        pma_inv_l3: "Business ID (NIB), Corporate Tax ID, & OSS RBA Access.",
        pma_get_t: "What Will You Receive?",
        pma_get_1: "Ministry Decree (SK)",
        pma_get_2: "Notarial Deed",
        pma_get_3: "Corporate Tax ID (NPWP)",
        pma_get_4: "NIB & OSS RBA Access",
        pma_svc_label: "Service",
        pma_price: "IDR 10,499,000",
        pma_btn_cta: "Free Consultation",
        pma_feat_1: "Fast & Legal Processing",
        pma_feat_2: "Process Monitoring via WhatsApp",
        pma_grnt_t: "Oerusin Guarantee:",
        pma_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        pma_badge: "合法性",
        pma_title: "外商独资/合资公司 (PT PMA)",
        pma_desc_t: "服务说明",
        pma_p1: "PT PMA（外商投资有限公司）是一种允许外国投资者（包括个人和海外公司）在印度尼西亚境内正式开展业务的法律实体形式。与本地公司相比，PT PMA 的设立受更具体的法规约束，包括遵守《投资正面清单》(DPI)。",
        pma_p2: "oerusin.id 的服务为全球投资者提供端到端的解决方案。我们处理所有的行政和官僚需求，从确定股权比例、办理公证契据，到获得司法部批文和 OSS RBA 合法资质。我们确保您的投资流程安全、快速，且完全符合印度尼西亚现行法律。",
        pma_adv_t: "PT PMA 的优势",
        pma_adv_l1: "外资所有权最高可达 100%（取决于行业/KBLI）。",
        pma_adv_l2: "全面进入印尼市场进行商业运营。",
        pma_adv_l3: "简化外籍员工有限居留许可 (KITAS) 的办理流程。",
        pma_inv_t: "我们的投资服务",
        pma_inv_l1: "《投资正面清单》(DPI) 咨询协助。",
        pma_inv_l2: "公司章程公证及司法部批准文件。",
        pma_inv_l3: "业务登记证 (NIB)、税号及 OSS RBA 访问权限。",
        pma_get_t: "您将获得什么？",
        pma_get_1: "司法部批文 (SK)",
        pma_get_2: "公证契据",
        pma_get_3: "企业税号 (NPWP)",
        pma_get_4: "NIB 和 OSS RBA 权限",
        pma_svc_label: "服务",
        pma_price: "10,499,000 印尼盾",
        pma_btn_cta: "免费咨询",
        pma_feat_1: "快速合法的办理",
        pma_feat_2: "通过 WhatsApp 监控进度",
        pma_grnt_t: "Oerusin 保证：",
        pma_grnt_d: "确保您的法律文件真实并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});