const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        ptumkm_badge: "Legalitas",
        ptumkm_title: "PT UMKM",
        ptumkm_desc_t: "Deskripsi Layanan",
        ptumkm_p1: "PT UMKM adalah pilihan tepat bagi Anda yang ingin membangun bisnis bersama partner atau rekan kerja dengan struktur organisasi yang lebih lengkap. Berbeda dengan PT Perorangan, PT UMKM didirikan oleh minimal dua orang pemegang saham dan memiliki pemisahan jabatan yang jelas antara Direktur dan Komisaris.",
        ptumkm_p2: "Layanan di oerusin.id mencakup pengurusan legalitas lengkap dari nol hingga perusahaan siap beroperasi. Kami memastikan Akta Notaris, SK Kemenkumham, hingga NIB Anda terbit dengan pemilihan kode KBLI yang paling menguntungkan.",
        ptumkm_adv_t: "Keunggulan PT UMKM",
        ptumkm_adv_l1: "Bisa memiliki lebih dari 1 pemegang saham.",
        ptumkm_adv_l2: "Struktur organisasi (Direksi & Komisaris) lebih kredibel.",
        ptumkm_adv_l3: "Akses modal perbankan dan investor terbuka luas.",
        ptumkm_pkg_t: "Paket All-In Oerusin",
        ptumkm_pkg_l1: "Sudah termasuk biaya Akta Notaris & SK.",
        ptumkm_pkg_l2: "NPWP Perusahaan & Akun OSS RBA.",
        ptumkm_pkg_l3: "Pendampingan hingga Sertifikat Standar.",
        ptumkm_get_t: "Apa yang Anda Dapatkan?",
        ptumkm_get_1: "Akta Notaris",
        ptumkm_get_2: "SK Kemenkumham",
        ptumkm_get_3: "NPWP",
        ptumkm_get_4: "KBLI OSS",
        ptumkm_svc_label: "Layanan",
        ptumkm_price: "Rp 4.999.000",
        ptumkm_btn_cta: "Konsultasi Gratis",
        ptumkm_feat_1: "Pengerjaan Cepat & Legal",
        ptumkm_feat_2: "Monitoring Proses via WA",
        ptumkm_grnt_t: "Garansi Oerusin:",
        ptumkm_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        ptumkm_badge: "Legality",
        ptumkm_title: "Regular PT (SME)",
        ptumkm_desc_t: "Service Description",
        ptumkm_p1: "Regular PT (SME) is the right choice for those who want to build a business with partners or colleagues with a more complete organizational structure. Unlike an Individual PT, a Regular PT is established by at least two shareholders and has a clear separation of roles between Directors and Commissioners.",
        ptumkm_p2: "Services at oerusin.id include complete legality management from scratch until the company is ready to operate. We ensure that the Notarial Deed, Ministry of Law Decree, and NIB are issued with the most advantageous KBLI codes.",
        ptumkm_adv_t: "Advantages of Regular PT",
        ptumkm_adv_l1: "Can have more than one shareholder.",
        ptumkm_adv_l2: "Credible organizational structure (Directors & Commissioners).",
        ptumkm_adv_l3: "Wider access to bank capital and investors.",
        ptumkm_pkg_t: "Oerusin All-In Package",
        ptumkm_pkg_l1: "Includes Notarial Deed & SK fees.",
        ptumkm_pkg_l2: "Company Tax ID & OSS RBA Account.",
        ptumkm_pkg_l3: "Assistance until Standard Certificate issuance.",
        ptumkm_get_t: "What Will You Receive?",
        ptumkm_get_1: "Notarial Deed",
        ptumkm_get_2: "Ministry of Law Decree (SK)",
        ptumkm_get_3: "Company Tax ID (NPWP)",
        ptumkm_get_4: "OSS KBLI Registration",
        ptumkm_svc_label: "Service",
        ptumkm_price: "IDR 4,999,000",
        ptumkm_btn_cta: "Free Consultation",
        ptumkm_feat_1: "Fast & Legal Processing",
        ptumkm_feat_2: "Process Monitoring via WhatsApp",
        ptumkm_grnt_t: "Oerusin Guarantee:",
        ptumkm_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        ptumkm_badge: "合法性",
        ptumkm_title: "普通有限责任公司 (PT UMKM)",
        ptumkm_desc_t: "服务说明",
        ptumkm_p1: "普通有限责任公司 (PT UMKM) 是希望与合作伙伴或同事建立具有更完整组织结构业务的人士的正确选择。与个人有限责任公司不同，普通公司由至少两名股东成立，并且董事和监事之间有明确的职责分工。",
        ptumkm_p2: "oerusin.id 的服务包括从零开始到公司准备运营的全套合法化办理。我们确保公证契约、司法部法令以及业务登记号 (NIB) 的签发均采用最有利的 KBLI 代码。",
        ptumkm_adv_t: "普通有限责任公司的优势",
        ptumkm_adv_l1: "可拥有多名股东。",
        ptumkm_adv_l2: "更具公信力的组织架构（董事会和监事会）。",
        ptumkm_adv_l3: "更广泛的银行资本和投资者准入渠道。",
        ptumkm_pkg_t: "Oerusin 全包套餐",
        ptumkm_pkg_l1: "已包含公证费和司法部法令费用。",
        ptumkm_pkg_l2: "公司纳税号和 OSS RBA 账户。",
        ptumkm_pkg_l3: "全程协助直至获得标准证书。",
        ptumkm_get_t: "您 akan 获得什么？",
        ptumkm_get_1: "公证契约",
        ptumkm_get_2: "司法部法令 (SK)",
        ptumkm_get_3: "公司纳税号 (NPWP)",
        ptumkm_get_4: "OSS 业务分类 (KBLI)",
        ptumkm_svc_label: "服务",
        ptumkm_price: "4,999,000 印尼盾",
        ptumkm_btn_cta: "免费咨询",
        ptumkm_feat_1: "快速合法的办理",
        ptumkm_feat_2: "通过 WhatsApp 监控进度",
        ptumkm_grnt_t: "Oerusin 保证：",
        ptumkm_grnt_d: "确保您的法律文件真实并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});