const translations = {
    id: {
        nav_home: "Home",
        nav_about: "Tentang",
        nav_services: "Layanan",
        nav_article: "Artikel",
        nav_contact: "Kontak Kami",
        cv_badge: "Legalitas",
        cv_title: "Persekutuan Komanditer (CV)",
        cv_desc_t: "Deskripsi Layanan",
        cv_p1: "Persekutuan Komanditer (CV) adalah bentuk badan usaha yang sangat populer bagi pengusaha di Indonesia karena proses pendiriannya yang lebih sederhana namun tetap memiliki legalitas yang diakui negara. CV didirikan oleh minimal dua orang, yang terbagi menjadi Sekutu Aktif (pengelola bisnis) dan Sekutu Pasif (pemberi modal).",
        cv_p2: "Layanan di oerusin.id membantu Anda melegalkan bisnis dalam bentuk CV dengan proses yang cepat dan transparan. Bentuk usaha ini sangat cocok bagi Anda yang ingin menjalankan bisnis jasa, perdagangan, atau kontraktor dengan biaya operasional legalitas yang lebih efisien dibandingkan PT.",
        cv_adv_t: "Keunggulan Mendirikan CV",
        cv_adv_l1: "Tidak ada minimal modal setor yang dipersyaratkan.",
        cv_adv_l2: "Sistem pengambilan keputusan yang lebih fleksibel.",
        cv_adv_l3: "Pajak yang relatif lebih simpel untuk UMKM.",
        cv_pkg_t: "Paket Lengkap CV",
        cv_pkg_l1: "Akta Notaris Pendirian CV.",
        cv_pkg_l2: "SK Pendaftaran dari Kemenkumham.",
        cv_pkg_l3: "NPWP Badan & NIB (OSS RBA).",
        cv_get_t: "Apa yang Anda Dapatkan?",
        cv_get_1: "SK Kemenkumham",
        cv_get_2: "Akta Notaris",
        cv_get_3: "NPWP Badan",
        cv_get_4: "NIB (OSS)",
        cv_svc_label: "Layanan",
        cv_price: "Rp 3.999.000",
        cv_btn_cta: "Konsultasi Gratis",
        cv_feat_1: "Pengerjaan Cepat & Legal",
        cv_feat_2: "Monitoring Proses via WA",
        cv_grnt_t: "Garansi Oerusin:",
        cv_grnt_d: "Dokumen legal Anda dipastikan asli dan terdaftar di sistem pemerintah.",
        whatsapp: "Konsultasi WhatsApp",
        cta_title: "Konsultasikan Legalitas Bisnis Anda Sekarang",
        cta_btn_contact: "Hubungi Kami →",
        cta_btn_service: "Lihat Layanan",
        footer_tagline: "Solusi legalitas dan perizinan bisnis terpercaya untuk pertumbuhan usaha Anda.",
        footer_menu_1: "Layanan",
        footer_link_pt: "Pendirian PT",
        footer_link_legal: "Legalitas Usaha",
        footer_link_permit: "Perizinan",
        footer_link_cek: "Cek Nama PT",
        footer_menu_2: "Perusahaan",
        footer_link_about: "Tentang",
        footer_link_article: "Artikel",
        footer_link_partner: "Partner",
        footer_menu_3: "Kontak",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privasi",
        footer_link_terms: "Syarat & Ketentuan",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_services: "Services",
        nav_article: "Article",
        nav_contact: "Contact Us",
        cv_badge: "Legality",
        cv_title: "Commanditarian Partnership (CV)",
        cv_desc_t: "Service Description",
        cv_p1: "A Commanditarian Partnership (CV) is a highly popular business entity for entrepreneurs in Indonesia due to its simpler establishment process while maintaining state-recognized legality. A CV is founded by at least two people, divided into Active Partners (business managers) and Passive Partners (investors).",
        cv_p2: "Services at oerusin.id help you legalize your business as a CV with a fast and transparent process. This business form is ideal for those in services, trading, or contracting who seek efficient legal costs compared to a Limited Liability Company (PT).",
        cv_adv_t: "Advantages of Forming a CV",
        cv_adv_l1: "No minimum paid-up capital requirement.",
        cv_adv_l2: "More flexible decision-making system.",
        cv_adv_l3: "Relatively simpler tax administration for SMEs.",
        cv_pkg_t: "CV Complete Package",
        cv_pkg_l1: "Notarial Deed of Establishment.",
        cv_pkg_l2: "Registration Decree from Ministry of Law.",
        cv_pkg_l3: "Corporate Tax ID (NPWP) & Business ID (NIB).",
        cv_get_t: "What Will You Receive?",
        cv_get_1: "Ministry Registration Decree",
        cv_get_2: "Notarial Deed",
        cv_get_3: "Corporate Tax ID",
        cv_get_4: "Business ID (OSS)",
        cv_svc_label: "Service",
        cv_price: "IDR 3,999,000",
        cv_btn_cta: "Free Consultation",
        cv_feat_1: "Fast & Legal Processing",
        cv_feat_2: "Process Monitoring via WhatsApp",
        cv_grnt_t: "Oerusin Guarantee:",
        cv_grnt_d: "Your legal documents are guaranteed to be authentic and registered in the government system.",
        whatsapp: "WhatsApp consultation",
        cta_title: "Consult Your Business Legality Now",
        cta_btn_contact: "Contact Us →",
        cta_btn_service: "View Services",
        footer_tagline: "Trusted business legality and licensing solutions for your business growth.",
        footer_menu_1: "Services",
        footer_link_pt: "PT Incorporation",
        footer_link_legal: "Business Legality",
        footer_link_permit: "Licensing",
        footer_link_cek: "Check PT Name",
        footer_menu_2: "Company",
        footer_link_about: "About Us",
        footer_link_article: "Articles",
        footer_link_partner: "Partners",
        footer_menu_3: "Contact",
        footer_copy: "© 2026 Oerusin. All rights reserved.",
        footer_link_privacy: "Privacy",
        footer_link_terms: "Terms & Conditions"
    },
    cn: {
        nav_home: "首页",
        nav_about: "关于我们",
        nav_services: "服务",
        nav_article: "文章",
        nav_contact: "联系我们",
        cv_badge: "合法性",
        cv_title: "有限合伙企业 (CV)",
        cv_desc_t: "服务说明",
        cv_p1: "有限合伙企业 (CV) 是印尼企业家非常受欢迎的商业实体形式，因为其设立程序更简单，同时仍具有国家承认的合法性。CV 至少由两人创立，分为活跃合伙人（业务管理者）和被动合伙人（投资者）。",
        cv_p2: "oerusin.id 的服务协助您通过快速透明的流程将业务合法化为 CV。这种业务形式非常适合希望在服务、贸易或承包领域运营，且与有限公司 (PT) 相比寻求更高效法律成本的人士。",
        cv_adv_t: "成立 CV 的优势",
        cv_adv_l1: "没有最低实缴资本要求。",
        cv_adv_l2: "更灵活的决策系统。",
        cv_adv_l3: "中小微企业税务处理相对简单。",
        cv_pkg_t: "CV 完整版套餐",
        cv_pkg_l1: "公证人设立契据。",
        cv_pkg_l2: "司法部登记批文 (SK)。",
        cv_pkg_l3: "企业税号 (NPWP) 和业务登记证 (NIB)。",
        cv_get_t: "您将获得什么？",
        cv_get_1: "司法部登记批文",
        cv_get_2: "公证人契据",
        cv_get_3: "企业税号",
        cv_get_4: "业务登记证 (OSS)",
        cv_svc_label: "服务",
        cv_price: "3,999,000 印尼盾",
        cv_btn_cta: "免费咨询",
        cv_feat_1: "快速合法的办理",
        cv_feat_2: "通过 WhatsApp 监控进度",
        cv_grnt_t: "Oerusin 保证：",
        cv_grnt_d: "确保您的法律文件真实并在政府系统中注册。",
        whatsapp: "WhatsApp咨询",
        cta_title: "立即咨询您的业务合法性",
        cta_btn_contact: "联系我们 →",
        cta_btn_service: "查看服务",
        footer_tagline: "为您业务增长提供值得信赖的法律和许可解决方案。",
        footer_menu_1: "服务项目",
        footer_link_pt: "成立有限责任公司 (PT)",
        footer_link_legal: "业务合法化",
        footer_link_permit: "许可申请",
        footer_link_cek: "核名查询",
        footer_menu_2: "公司信息",
        footer_link_about: "关于我们",
        footer_link_article: "文章咨询",
        footer_link_partner: "合作伙伴",
        footer_menu_3: "联系方式",
        footer_copy: "© 2026 Oerusin. 版权所有。",
        footer_link_privacy: "隐私政策",
        footer_link_terms: "服务条款"
    }
};

function switchLanguage(lang) {
    // Simpan pilihan bahasa ke localStorage agar tidak reset saat pindah halaman
    localStorage.setItem('selectedLang', lang);

    // Cari semua elemen yang punya atribut data-key
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });
}

// Jalankan fungsi saat halaman dimuat
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'id';
    switchLanguage(savedLang);
});